### ISSUE TITLE
Optimize performance of LDAP queries for bundle/service properties

### ISSUE THREAD

**Issue by kevinleeMW** [CppMicroServices/CppMicroServices#101]
This issue entails a follow-up task of "Support LDAP queries against bundle meta-data" (Issue #53):

Optimizing the performance of LDAP queries. (e.g. string length comparison for exact string match)

**Comment by jeffdiclemente** [comment]
closing as this issue is very old and performance of LDAP queries was partially addressed in PR #389.

New issues will be created for improving the performance of LDAP queries, if required.
