### ISSUE TITLE
Add event admin plugin.

### ISSUE THREAD

**Issue by lygstate** [CppMicroServices/CppMicroServices#104]

**Comment by saschazelzer** [comment]
Is this a feature request, or do you want to contribute such a bundle?

**Comment by lygstate** [comment]
@saschazelzer I'd  like to contribute, I didn't see any standard us plugins, where are they?

**Comment by saschazelzer** [comment]
There are only a few experimental bundles in the development branch, like httpservice and webconsole. Currently, the focus is still on improving the framework itself.

**Comment by jeffdiclemente** [comment]
@lygstate This is great. We welcome contributions. The event admin would be a very useful addition.

**Comment by achristoforides** [comment]
This will be tracked in https://github.com/CppMicroServices/CppMicroServices/issues/687
