### ISSUE TITLE
support building for Android

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#106]
The use of certain C++11 string functions, such as ```std::to_string```, are not supported in the latest Android NDKs.

**Comment by saschazelzer** [comment]
Could you elaborate a little more about the general state of Android support? Is that something you were looking at, and if yes what else would be missing? Is it something we should support officially (by listing it as a supported platform in the readme file)?

**Comment by jeffdiclemente** [comment]
We support Android, iOS and linux-arm. Our requirement is that CppMicroServices does need to build and run on these platforms.

The general state of CppMicroServices support was that it was working for our usage up until the introduction of ```std::to_string``` (which is perfectly fine and should not hinder the use of C++11 string conversion functions). Currently only Android is broken.
We've dealt with the same situation before (i.e. missing C/C++ functions in Android). The typical solution is to implement the missing function and bring it into the ```std::``` namespace such that clients don't know the difference.

I think its worth officially stating that Android and iOS are supported. 
We haven't done extensive testing of CppMicroServices on these platforms yet, so I think that's worth mentioning in any statement of support (e.g. not heavily tested in production environment, etc...).

FYI; We have a short term cmake solution to perform cross platform builds of CppMicroServices for these platforms. It simply involves using the correct resource compiler binary for the host build platform. We haven't had the bandwidth to refine the solution and submit it yet. That's coming soon.

**Comment by kevinleeMW** [comment]
closed with PR #111
