### ISSUE TITLE
Crash when trying to access bundle context.

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#110]
The following code produces EXEC_BAD_ACCESS on Mac OS X.

```
FrameworkFactory factory;
auto f = factory.NewFramework(configuration);
auto fmc = f.GetBundleContext();
f.start();
```
User's should not be able to retrieve the framework's bundle context before the framework has started, but the function should not crash.

**Comment by saschazelzer** [comment]
Good catch. The function now returns an invalid context if the framework has not been initialized yet.
