### ISSUE TITLE
Investigate using std::unique_ptr<LogSink> instead of shared_ptr

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#113]
The `CoreBundleContext` object is really the sole owner of the `LogSink` object. The `LogSink` object is temporarily used by the `LogMsg` object during its lifetime to write messages to an IO stream.

This issue captures the investigation and resolution on whether `std::shared_ptr<LogSink>` in `usCoreBundleContext_p.h` can be replaced with `std::unique_ptr<LogSink>`?

**Comment by achristoforides** [comment]
This change has been made.
