### ISSUE TITLE
Mac OS X and iOS code signing failures

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#114]
Appending meta-data to the end of a binary causes code signing failures for Mac OS and iOS.

See [OS X Code Signing In Depth](https://developer.apple.com/library/mac/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG309) for details.

using the -sectcreate linker option appears to be a valid solution to this issue as it doesn't invalidate the code signing.

To keep inline with Mac OS and iOS standards we should come up with a long term solution to ensure that meta-data can be embedded in binaries and still pass code signing on Mac OS and iOS.

**Comment by saschazelzer** [comment]
Exactly, that is why the CMake scripts use "link mode" as the default on Mac OS, see this comment https://github.com/CppMicroServices/CppMicroServices/blob/development/cmake/usFunctionEmbedResources.cmake#L14. Or did I miss something?

**Comment by jeffdiclemente** [comment]
You are correct. I was talking to @karthikreddy09  today and there may be some edge cases with the "link mode" method that we need to investigate. At the moment its unclear if there are any issues with "link mode". We are working on investigating it after the 3.0 release

**Comment by karthikreddy09** [comment]
The "link mode" does work for iOS. We initially recommended the "append mode" at The Mathworks, since it was the simpler to integrate with our build system but now that we have run into issues, we are switching to "link mode".

**Comment by jeffdiclemente** [comment]
ok. @karthikreddy09 if there are no bugs with how CppMicroServices does "link mode", you can close this issue.

**Comment by karthikreddy09** [comment]
Not a bug !!
