### ISSUE TITLE
Trying to stop the bundle returned by GetBundle(0) causes a crash

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#121]
The following code causes a crash on Mac OS X. Haven't tried on other platforms.

```
void TestIndirectFrameworkStop()
{
    auto f = FrameworkFactory().NewFramework();
    f.Start();
    auto bundle = f.GetBundleContext().GetBundle(0);
    bundle.Stop(); // crashes here
    US_TEST_CONDITION(f.GetState() != Bundle::STATE_ACTIVE, "Framework failed to stop");
}
```

I understand why the above bundle.Stop() does not call Framework::Stop() method but is this expected ?

At the very least, it should not crash.

**Comment by saschazelzer** [comment]
Uh, that is a nasty one. You are right, the current implementation does not call `Framework::Stop()` when calling `Stop()` on the a `Bundle` instance that represents the system bundle. That is definitely a bug and a severe one. The problem extends to all other methods that the `Framework` class intends to override. This was introduced when we made the `Bundle` and `BundleContext` classes value-types.
