### ISSUE TITLE
ResourceCompiler fails to embed manifest when using --bundle-file and --manifest-add together

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#124]
This has only been reproduced on Windows.

When running the following command

```
ResourceCompiler.exe -v -n %bundle name% -b %absolute path to a .dll% -m manifest.json
```

The resource compiler fails to embed the manifest with an error similar to

> Opening file .\ZIP1.tmp failed
Error removing temporary zip archive .\ZIP1.tmp

even if the ```-o/--out-file``` option is used to specify a ZIP file, it still fails to embed the ZIP file.

A workaround is to call ResourceCompiler two times; once to create the ZIP file using the ```-o/--out-file``` option and second to embed the ZIP file using the ```-z/--zip-add``` option,

Also, tests should be written to ensure the ResourceCompiler works as designed.

**Comment by karthikreddy09** [comment]
Fixed in PR#141
