### ISSUE TITLE
Build failure on Mac due to namespace confusion

### ISSUE THREAD

**Issue by kevinleeMW** [CppMicroServices/CppMicroServices#128]
The framework fails to build on Mac, due to namespace confusion in `framework/src/util/Utils.cpp`

One of the error messages:
"No type named 'string' in namespace 'cppmicroservices::std'; did you mean '::std::string'?"

Abhinay and I determined that this happens, because of the following lines that are inside the `cppmicroservices` namespace:

#ifdef US_HAVE_CXXABI_H
#include <cxxabi.h>
#endif

Simply moving this #include statement outside the namespace seems to resolve the issue.

**Comment by jeffdiclemente** [comment]
If we use travis CI to build for OS X, we can catch these failures much earlier.
