### ISSUE TITLE
Examples are broken due to "bundle.symbolic_name" change

### ISSUE THREAD

**Issue by kevinleeMW** [CppMicroServices/CppMicroServices#130]
Example bundles' manifest.json files still have "bundle.name" properties, which need to be updated to "bundle.symbolic_name".

**Comment by karthikreddy09** [comment]
Working on it .... "l"(load) & "u"(unload) don't make much sense for v3.0.
I am going to refactor the commands as well

**Comment by saschazelzer** [comment]
I was working a little bit on the usShell (making it work in static build mode) and was thinking if we could get rid of the the example driver and its custom command line and just use the usShell as the "driver" instead. It already has proper install/start/stop commands. I am not sure how the dictionary service would behave in the shell REPL though... I would have to check / try.

What do you think?

**Comment by jeffdiclemente** [comment]
I like this idea. +1.

**Comment by karthikreddy09** [comment]
+1 ... 

I will submit the changes to manifest files and leave the driver as is.

For the dictionary client, how about spawning a separate UI thread from the client's activator start method ? A separate window can be displayed using the spawned thread. when the client bundle is stopped, the UI thread will be terminated ...

**Comment by saschazelzer** [comment]
Okay, thanks for fixing the manifest files.

While your idea is nice, I wouldn't want to look into cross-platform UI development just yet. Ideally, the examples should work in any console session without even an UI available to it, in my opinion.

**Comment by jeffdiclemente** [comment]
I agree with Sascha, lets keep it simple with the examples.

**Comment by saschazelzer** [comment]
As discussed, we should try to fix the examples driver for the 3.0 release and investigate a usShell based solution later.

**Comment by saschazelzer** [comment]
@karthikreddy09  @ksubramz Did you guys start to work on this one? If not, I could take it over.

**Comment by karthikreddy09** [comment]
I do not have any existing work for this one. Feel free to take over.
