### ISSUE TITLE
Fix linker warning on OS X

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#137]
Found the following in travis build logs for OS X. Maybe revert to `us_resources` ?

`ld: warning: -seccreate section name (cppmicroservices_resources) truncated to 16 chars (cppmicroservices)`

**Comment by saschazelzer** [comment]
I saw this as well. I agree with reverting to `us_resources`.

**Comment by karthikreddy09** [comment]
Fixed in PR#140
