### ISSUE TITLE
ShrinkableMap allows addition or modification of keys

### ISSUE THREAD

**Issue by ksubramz** [CppMicroServices/CppMicroServices#154]
## Description

ShrinkableMap's operator[] uses the operator[] of the underlying std::map member

```
T& operator[](const Key& key)
{
  return container[key];
}
```

However, the effect of using operator[] ..  

> If there is no key equivalent to x in the map, inserts value_type(x, T()) into the map

This means that it's possible to add keys to the ShrinkableMap as evidenced by the code segment below (courtesy: @karthikreddy09 )

```
ShrinkableMap<int, int> myMap;
int x = myMap[10];
std::cout << "value of x is " << x << std::endl;
std::cout << "size of shrinkable map is " << myMap.size() << std::endl;
US_TEST_CONDITION(myMap.size() == 0, "Map size should not grow”);
```

The bug is that ShrinkableMap allows addition of keys and modification of mapped values using  the operator[].

About the modification of the mapped values, the relevant part is from the [OSGI spec sections discussing shrinkable collection](https://osgi.org/download/r6/osgi.core-6.0.0.pdf#page=370) 

> "A shrinkable collection is a Collection that supports all remove operations. Any other attempts to modify a shrinkable collection will result in an UnsupportedOperationException being thrown."
## Proposal

To fix the issue (preclude both the addition and modification parts):
1. Remove operator[] from ShrinkableMap
2. Implement at() method which returns a const T& (where T is mapped_type)
#### Rationale
1. This is so that the ShrinkableMap interface is consistent with std::map, where operator[] can either modify the value of an existing key or insert a key.
2. ShrinkableMap::at() method would use the std::map::at() (from C++11). Note that the std::map::at() simply returns a reference to the mapped value. There are two overloaded methods - one returning plain reference and the other returning const reference and by not implementing the method which returns a plain reference, we preclude the modification of the mapped_value.
3. std::map::at() method throws out_of_range exception if no such key is present and in effect, the proposed ShrinkableMap::at() throws that too i.e  we don't need to explicitly throw out_of_range exception and we can simply document this in the .at() method of ShrinkableMap - again consistent with std::map.

Appreciate your thoughts on this

**Comment by saschazelzer** [comment]
Thanks for the detailed report. I fully agree. Are you willing to provide a PR to fix this issue according to your proposal?

**Comment by ksubramz** [comment]
Thanks Sascha! I can certainly provide a PR.
