### ISSUE TITLE
Any::ToString crashes if the object is empty.

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#155]
The method should minimally throw an exception but not crash if the object is empty.

**Comment by saschazelzer** [comment]
Agreed, it should not crash. I am not sure if throwing is the best approach. Having a `ToString()` method that always returns a `std::string` seems nice to me when generically handling any `Any` instance. It could print `<empty>` or similar. Code acting differently on an empty Any would likely check for emptiness via `Empty()` before anyway.

**Comment by saschazelzer** [comment]
I am going to work on this, @karthikreddy09 if you started already please tell me.

As discussed, I will add a second method named `ToStringNoExcept()` which does not throw and fix the current `ToString()` method to throw if the Any is empty.

**Comment by karthikreddy09** [comment]
Thanks @saschazelzer  !!
