### ISSUE TITLE
Add integration tests for ResourceCompiler

### ISSUE THREAD

**Issue by ksubramz** [CppMicroServices/CppMicroServices#162]
The tests are needed so that any changes to ResourceCompiler don't cause a surprising change in behavior. The bare minimum requirements are 

- Test injecting a manifest inside a bundle
- Test injecting any file into the zip blob
- If there's already a zip blob, test the merging (--zip-add)
- Test --bundle-file option (whether an archive is appended to the bundle)

Some extra comments:
- We need some sort of zipinfo mechanism to query the contents inside the bundle
- We can use CTests to do the testing

**Comment by jeffdiclemente** [comment]
marking as closed by #169
