### ISSUE TITLE
Builds failing in Debian 8.3

### ISSUE THREAD

**Issue by ksubramz** [CppMicroServices/CppMicroServices#163]
I encountered 2 classes of build errors (due to warnings) in Debian 8.3 (GCC version 4.9.2).

1. unused variable. I initially bumped into it because in a few places instead of US_UNUSED(l) - letter L, we have US_UNUSED(1) - numeral 1.
```
framework\include\cppmicroservices\detail\Log.h
56:    auto l = Lock(); US_UNUSED(1);

framework\src\service\ServiceListeners.cpp
143:  auto l = frameworkListenerMap.Lock(); US_UNUSED(1);
153:  auto l = frameworkListenerMap.Lock(); US_UNUSED(1);
242:    auto l = frameworkListenerMap.Lock(); US_UNUSED(1);
```
Interestingly, I am not bumping into this anymore. (even with a clean CMake build directory). However, we do need to fix these.

2. missing-field-initializer
```
In file included from /home/krishs/Github/CppMicroServices/framework/src/bundle/BundleThread.h:27:0,
                 from /home/krishs/Github/CppMicroServices/framework/src/bundle/BundleThread.cpp:23:
/home/krishs/Github/CppMicroServices/framework/include/cppmicroservices/detail/Threads.h: In instantiation of ‘cppmicroservices::detail::Atomic<T>::Atomic() [with T = cppmicroservices::BundleEventInternal]’:
/home/krishs/Github/CppMicroServices/framework/src/bundle/BundleThread.cpp:46:15:   required from here
/home/krishs/Github/CppMicroServices/framework/include/cppmicroservices/detail/Threads.h:187:11: error: missing initializer for member ‘cppmicroservices::BundleEventInternal::type’ [-Werror=missing-field-initializers]
     : m_t{}
           ^
/home/krishs/Github/CppMicroServices/framework/include/cppmicroservices/detail/Threads.h:187:11: error: missing initializer for member ‘cppmicroservices::BundleEventInternal::bundle’ [-Werror=missing-field-initializers]
cc1plus: all warnings being treated as errors
```
When initializing `detail::Atomic<BundleEventInternal> be` BundleThread.h, gcc warns is about not initializing BundleEventInternal members. Some relevant information here? https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55805 . Clearly, this hasn't failed in our CI systems so likely it's a compiler version specific issue.

**Comment by saschazelzer** [comment]
Thanks for reporting this. I pushed branch 163-workaround-gcc49-warning which I tested on Ubuntu Trusty with gcc 4.6 and gcc 4.9 and on Fedora 24 with default gcc and clang.

Could you check if it compiles cleanly on your Debian machine?

**Comment by ksubramz** [comment]
Thanks for fixing these promptly. Confirming that these changes fix the build issues in Debian machine.
