### ISSUE TITLE
Add Visual Studio 2010 support.

### ISSUE THREAD

**Issue by lygstate** [CppMicroServices/CppMicroServices#166]

**Comment by jeffdiclemente** [comment]
@lygstate , our supported minimum compiler version is VS 2013. We've moved the minimum compiler so we can leverage many useful C++11 features.
There are no plans to support VS 2010.
Are there any specific challenges in using VS 2013 instead of 2010?

**Comment by lygstate** [comment]
@jeffdiclemente Vs2010 is the lastest compiler can debugging on Windows XP.

**Comment by saschazelzer** [comment]
VS 2010 was supported in the 2.x versions, but as Jeff said we dropped support for it intentionally. You could either stick with 2.x or build your binaries on Windows 7 using VS 2013 targeting Windows XP. If you really need to debug running applications directly on Windows XP, you should be able to use VS 2010 just for the debugging task.
