### ISSUE TITLE
Fix ResourceCompilerTest failures

### ISSUE THREAD

**Issue by ksubramz** [CppMicroServices/CppMicroServices#171]
In the pull request #169, ResourceCompilerTest run in Travis result in test failures. The failure specifically is of the form:
```
37: Test command: /tmp/us\ builds/CppMicroServices_shared-threading\ (Unix\ Makefiles)/bin/usFrameworkTestDriver "ResourceCompilerTest"
37: Test timeout computed to be: 600
37: sh: 1: Syntax error: "(" unexpected
37: Cmdline invocation in testManifestAdd returns 0 [FAILED]
37:   +--> in /home/travis/build/CppMicroServices/CppMicroServices/framework/test/ResourceCompilerTest.cpp, line 133, expression is false: "ret == 0"
```

This is what's happening - the test internally uses several invocations of ResourceCompiler command line to test various features and it uses `std::system` to do the invocation. Looks like its behavior is similar to https://linux.die.net/man/3/system -- basically invokes the whole command using `/bin/sh -c` and since the path of the usFrameworkTestDriver contains parenthesis, the `sh` command results in a syntax error and the std::system call doesn't run.

**Comment by ksubramz** [comment]
Tried bracketing the command line with single quotes and double quotes but that didn't work. At this point, I think a more robust and a better way to test ResourceCompiler is to directly construct the command line pass them (say vector<string> of them) to a function in ResourceCompiler. This function will be called both by
- entry point main(), when ResourceCompiler is invoked as a command line, where main() will provide the argv and argc
- usFrameworkTestDriver calling this function and provide the argc and argv
The rest of the argument parsing happens in this function 

An added advantage is std::system usage is generally discouraged and this seems more idiomatic. Would love your thoughts?

**Comment by saschazelzer** [comment]
Before we go this route, I think we (you) should still try to escape and quote the `std::system` argument properly. This can be a little tricky to get right. For example, an invocation of the cmd `/tmp/path (space)/rc` with the argument `hello.txt` needs to look like:
```
std::system("/tmp/path\\ \\(space\\)/rc hello.txt");
```
as tested on my Linux machine.

**Comment by ksubramz** [comment]
With the latest commit (https://github.com/ksubramz/CppMicroServices/commit/453953eda0138e396fe2e5b69c4402fb8062706a), I was finally successful in getting the tests to work in Travis. Thanks Sascha for the helpful suggestion.

However, before Sascha's suggestion I was tempted to try out the alternate proposal (which was proposed yesterday) and I have a functional but incomplete implementation in the branch rc_as_library - https://github.com/ksubramz/CppMicroServices/commit/1c181cd8356cf18059eb17cb36156d950e3f44e3

In this method, most of the functionality of ResourceCompiler is factored out to a library and the ResourceCompiler executable is a thin wrapper around the library (https://github.com/ksubramz/CppMicroServices/commit/1c181cd8356cf18059eb17cb36156d950e3f44e3#diff-7ff13f6c944f78f9c336c27923259760). The test driver also links with ResourceCompiler and instead of explicitly invoking the command line using std::system, the command is passed to the `ResourceCompiler()` function as argc and argv.

**Pros:**
 - We no longer use std::system and no longer dependent on the fact that ResourceCompiler and the test driver executable are in the same directory. 
 - Less OS vagaries (like this fault, for example). And the test is more robust in different platforms because we operate in C++ space.
**Cons:**
 - The actual invocation of ResourceCompiler executable is not tested (however, since we construct the command as a vector<string> and pass argc and argv to the ResourceCompiler() function we are testing _almost_ the entire thing)

Here are the pros and cons of the older (already implemented) approach
**Pros:**
 - Tests the entire functionality i.e. starting from the command line invocation itself.
 - Already implemented (though, the completion of the other implementation shouldn't take long).
**Cons:**
 - Similar issues may arise in future due to different platforms.

**Comment by saschazelzer** [comment]
Personally, since it works now, I would keep it as it is (it is a trade off between keeping the resource compiler code and build system simple or the test infrastructure). If we find another use cases for having a resource compiler library (except for making tests less error prone) or if we run into more problems with the tests, it will be good to have your branch handy.

**Comment by karthikreddy09** [comment]
I agree with @saschazelzer  ...

**Comment by jeffdiclemente** [comment]
I agree with @saschazelzer and @karthikreddy09, let's invoke the tests using ```std::system```.

@ksubramz Thanks for exploring the other option. I'd suggest keeping that code around in a separate branch for now.

**Comment by ksubramz** [comment]
Thanks all, and agree with all of you.
