### ISSUE TITLE
potential race condition in ServiceHooks.cpp

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#173]
There is a potential race condition between ```ServiceHook::Open()``` and ```ServiceHooks::Close()``` when accessing ```listenerHookTracker```. 

```
void ServiceHooks::Open()
{
  {
    auto l = this->Lock(); US_UNUSED(l);
    listenerHookTracker.reset(new ServiceTracker<ServiceListenerHook>(GetBundleContext(), this));
  }
  listenerHookTracker->Open();

  bOpen = true;
}

void ServiceHooks::Close()
{
  auto l = this->Lock(); US_UNUSED(l);
  if (listenerHookTracker)
  {
    listenerHookTracker->Close();
    listenerHookTracker.reset();
  }

  bOpen = false;
}
```

Per a discussion with Sascha, the lock cannot be moved since a call to ```listenerHookTracker->Open();``` can result in calling into user callback code and risking a deadlock.

**Comment by saschazelzer** [comment]
I have looked at this again and think I was mistaken. Or I do not remember my reasoning.

The `Open()` and `Close()` functions are called during framework initialization and shutdown. Before `Open()` is called, no bundles are started yet, so there are no `ServiceListenerHook` services that might be called when opening the tracker. Likewise, before `Close()` is called during framework shutdown, all bundles are stopped. Hence there are no `ServiceListenerHook` services registered anymore. So overall, no user callbacks are called at this point. Unless I have missed something. Therefore, I propose to extend the locks to cover the complete function body. Local test runs are looking good. Thoughts?

**Comment by jeffdiclemente** [comment]
I took a look over the code as well and I agree with you. Extending the scope of the lock looks good to me.
