### ISSUE TITLE
The resource compiler should perform at least minimal validation of a manifest prior to embedding

### ISSUE THREAD

**Issue by tmwnewbold** [CppMicroServices/CppMicroServices#182]
The resource compiler should perform at least minimal validation (perhaps simple syntax checking) of JSON manifests prior to embedding them into bundles. At it stands right now, even simple typos in a manifest result in total runtime failure of the product-- see #180. Even when #180 is fixed, it is still extremely wasteful to not be able to detect basic issues with manifest files until runtime.

**Comment by saschazelzer** [comment]
Very good point, thanks for reporting this.
