### ISSUE TITLE
Bundle::GetProperty() is deprecated and says to use Bundle::GetHeaders()--which is awkward

### ISSUE THREAD

**Issue by tmwnewbold** [CppMicroServices/CppMicroServices#183]
Bundle::GetPropery() let's you query for a single property value. Bundle::GetHeaders() returns them all in an AnyMap. The latter is really awkward to use if you're just interested in a single value which may or may not exist in the map. From what I can see the only way to look for an optional value _without_ having to deal with exceptions is to use find(), and then you get all tangled up with iterators and multiple lines of code.

**Comment by saschazelzer** [comment]
The `AnyMap` class has a similar interface as the standard STL containers. Typical code would look like
```
auto iter = anymap.find("key");
if (iter != anymap.end())
{
  // found
}
```
just like for a `std::map` for example. Could you give an example what you would like to have instead?

**Comment by saschazelzer** [comment]
Closing this because of a lack of feedback.
