### ISSUE TITLE
Using https://github.com/nlohmann/json instead of any&anymap.

### ISSUE THREAD

**Issue by lygstate** [CppMicroServices/CppMicroServices#194]

**Comment by jeffdiclemente** [comment]
@lygstate This json library looks very full featured. CppMicroServices supports GCC 4.6 and this json library starts with GCC 4.9.3.

**Comment by saschazelzer** [comment]
While I understand the desire to have a nice JSON API for some use cases, this library does not match our current minimum compiler version requirements.

In addition, we need to carefully consider which external libraries we are going to expose in our public API if we (for example) would replace `Any` and `AnyMap` with it. In this particular case, the classes are also used in a non-JSON context (e.g. framework properties) so there are even more things to consider.

Closing this for now, maybe reconsider for 4.0.
