### ISSUE TITLE
unsafe_any_cast is broken.

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#197]
The following snippet results in compilation error

```
int val = 10;
Any anyInteger(val);
int* valPtr = unsafe_any_cast<int>(&anyInteger);
```

> Any.h:539:11: error: cannot cast from type 'std::unique_ptr<Placeholder>' to pointer type 'Any::Holder<int> *'
>   return &static_cast<Any::Holder<ValueType>*>(operand->_content)->_held;
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Test.cpp:154:17: note: in instantiation of function template specialization 'cppmicroservices::unsafe_any_cast<int>' requested here
>   int* valPtr = unsafe_any_cast<int>(&anyInteger);
>                 ^
> 1 error generated.

**Comment by ksubramz** [comment]
This seems to work. (Code borrowed from the safe alternative: `any_cast`).

```diff
-  return &static_cast<Any::Holder<ValueType>*>(operand->_content)->_held;
+  return &static_cast<Any::Holder<ValueType>*>(operand->_content.get())->_held;
```

Interestingly, the Boost Any.h still seems to have the same issue, however I can't find any bugs related to this :  http://www.boost.org/doc/libs/1_57_0/boost/any.hpp
