### ISSUE TITLE
[Linux] Test failure caused by temporary directory name collisions

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#220]
I recently saw a use case whereby a BundleTest test point failed while creating the framework's temporary storage directory. 
The failure was a seg fault and when it was traced back, the fault was that the temp storage directory already existed with permissions that did not allow r/w access to the current user. 
For example, ```/tmp/data``` already existed and the "local" sub directory couldn't be created because ```/tmp/data``` wasn't r/w for the user running the test (the machine is used by many different users).

For Linux, the test code should use a standard POSIX system API, like [mkdtemp](http://pubs.opengroup.org/onlinepubs/9699919799/functions/mkdtemp.html) instead of querying the ```TMPDIR``` env var. This helps to avoid directory name collisions.

**Comment by saschazelzer** [comment]
I am going to fix this as part of my work on #191.
