### ISSUE TITLE
JSON uses case sensitive keys, BundleManifest uses a case insensitive unordered map

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#237]
This is a discussion point; JSON uses case sensitive key names yet CppMicroServices stores manifest.json key/values in a case insensitive unordered map.

My question is; given that we use JSON, instead of the jar manifest file format that OSGi assumes, should we be consistent with JSON in terms of case sensitivity?

As an example:

If you have the following manifest.json, 
 
```
{
  “bundle.name": "foo", 
  "bundle.version" : "1.0.2",
  "bundle.description" : "This bundle is broken!",
  "authors" : ["John Doe", "Douglas Reynolds", "Daniel Cannady"],
  "Bundle.name" : "foobar",
  "rating" : 5
}
```
 
Querying for ```Bundle.name``` or ```bundle.name``` will always return ```foobar```.

Thoughts?

**Comment by saschazelzer** [comment]
I think it depends also on our view about LDAP filters and how they should match attribute names. Typically, LDAP attribute names are case insensitive, which is also how we normally evaluate if a filter matches a set of properties or a bundle (using its manifest headers).

I believe the OSGi manifest headers are case insensitive for various reasons, one being the fact that LDAP filters should be applicable in straight-forward way, matching case-insensitive by default.

Changing to case-sensitive behavior would be more natural for JSON itself, but then I think we need to make LDAP filters case-sensitive by default as well.

**Comment by jeffdiclemente** [comment]
I see, I didn't know LDAP filters were case-insensitive by default. 
Based on reading https://www.ldap.com/ldap-filters, it looks like case sensitive matching can occur with LDAP filters (using extensible match filters).

I could see cases where users run into LDAP query issues caused by case sensitivity. Perhaps adding documentation explaining case sensitivity between JSON and LDAP is sufficient for know?

**Comment by saschazelzer** [comment]
I agree that we should at least document the interplay of JSON based bundle manifests, case-sensitivity, and LDAP filters. Do you have someone in mind to assign this task to?

**Comment by jeffdiclemente** [comment]
I will take the task of documenting the interaction between JSON and LDAP.

**Comment by jeffdiclemente** [comment]
closing discussion
