### ISSUE TITLE
IsConvertibleTo method doesn't check for validity of member

### ISSUE THREAD

**Issue by ksubramz** [CppMicroServices/CppMicroServices#240]
## The Issue
The method in question:
```cpp
bool ServiceReferenceBasePrivate::IsConvertibleTo(const std::string& interfaceId) const
{
  return registration ? registration->Lock(), registration->service->find(interfaceId) != registration->service->end() : false;
}
```
The member `service` of `registration` is an `InterfaceMapConstPtr`, which could be `reset()` by another thread calling Unregister() on the `ServiceRegistration` object [[1](https://github.com/CppMicroServices/CppMicroServices/blob/development/framework/src/service/ServiceRegistrationBase.cpp#L260)]. When the current thread dereferences `service` i.e. `registration->service->find()`, it results in a crash (access violation).

## Minimal Test Case

Minimal test case to illustrate the crash

```cpp
void TestUnregisterRace(BundleContext context)
{
  struct TestServiceA : public ITestServiceA
  {
  };

  auto s1 = std::make_shared<TestServiceA>();

  std::atomic_bool done(false);
  auto copyRefs = [](ServiceReference<ITestServiceA> ref, std::atomic_bool& done) {
	  while (!done)
	  {
	      (void)ref.IsConvertibleTo("IBooService");
	  }
  };
  
  ServiceRegistration<ITestServiceA> registration = context.RegisterService<ITestServiceA>(s1);
  ServiceReference<ITestServiceA> reference = context.GetServiceReference<ITestServiceA>();
  std::thread thread(copyRefs, reference, std::ref(done));
  std::this_thread::sleep_for(std::chrono::milliseconds(10));
  registration.Unregister();
  std::this_thread::sleep_for(std::chrono::milliseconds(10));
  done = true;
  thread.join();
}
```

* The main thread registers a service with ServiceReference reference, spawns a thread copyRefs, waits for a bit and calls Unregister() on the ServiceRegistration object registration.
* The spawned thread keeps calling IsConvertibleTo() on reference object until the main thread flips the bool "done", which in turn signals the thread to stop.
* The crash happens as soon as the Unregister() is invoked on the registration object.

## Fix Proposal

The fix simply checks for the validity of `service` member before dereferencing it.

```cpp
bool ServiceReferenceBasePrivate::IsConvertibleTo(const std::string& interfaceId) const
{
  if (registration)
  {
	  auto l = registration->Lock(); US_UNUSED(l);
	  return registration->service ? registration->service->find(interfaceId) != registration->service->end() : false;
  }
  return false;
}
```
This has been tested and the minimal test case program runs successfully.

### A tangential question
In general use case, it seems to me that the check for `registration` in `IsConvertibleTo` will always evalute to `True` because it's a non-null pointer. Is my assumption correct? Is there a case where `registration` is nullptr?

**Comment by karthikreddy09** [comment]
A tangential question

In general use case, it seems to me that the check for registration in IsConvertibleTo will always evalute to True because it's a non-null pointer. Is my assumption correct? Is there a case where registration is nullptr?

>> IMO, checking for null before dereferencing a pointer is always the right thing to do.  In the current state of the framework code, it may be true that registration member of ServiceReferenceBasePrivate objects is always non-null but if you look at the class ServiceReferenceBasePrivate in isolation, it is possible the registration member could be a nullptr. Hint: Constructor.

-Abhinay.

**Comment by ksubramz** [comment]
Thanks Abhinay. I didn't look carefully. Indeed, an invalid ServiceReference object has "registration" = nullptr.
