### ISSUE TITLE
Extend module life-cycle states

### ISSUE THREAD

**Issue by saschazelzer** [CppMicroServices/CppMicroServices#25]
The work related to issue #15 allows the retrieval of module properties without loading the module's shared library. This leads to new module life-cycle states, e.g. to be able to access a module's properties, it must first be *installed* into the system to be known to other modules.

**Comment by jeffdiclemente** [comment]
Does merging [https://github.com/saschazelzer/CppMicroServices/issues/31](https://github.com/saschazelzer/CppMicroServices/issues/31) resolve this issue?

**Comment by saschazelzer** [comment]
Done with PR #105 .
