### ISSUE TITLE
build error with VS2017

### ISSUE THREAD

**Issue by michkrom** [CppMicroServices/CppMicroServices#265]
Encountered a build error on VS2017. Looks like a premature template expansion by VS compiler.

C:\git\CppMicroServices\framework\include\cppmicroservices/ServiceInterface.h(145): error C2027: use of undefined type 'cppmicroservices::HttpServlet' (compiling source file C:\git\CppMicroServices\httpservice\src\ServletContext.cpp)

The workaround is to add the following #include to ServletContainerPrivate.h:

#include "cppmicroservices/httpservice/HttpServlet.h"

**Comment by zacklj89** [comment]
Ran into the same issue using MSVC 15.6.5

**Comment by saschazelzer** [comment]
Fixed in the development branch.
