### ISSUE TITLE
Permissions issues in %TEMP%\data directory causes CppMicroServices to fail

### ISSUE THREAD

**Issue by ksubramz** [CppMicroServices/CppMicroServices#266]
# Reproduction Steps

Under Windows,
## First
1. Make the directory `%TEMP%\data (C:\Users\<username>\AppData\Local\Temp\data)` inaccessible. (Right click and deny all access control for the user)
2. Run the gtests.  `FrameworkTest.CustomConfiguration` test will fail (the test sets the `FRAMEWORK_STORAGE` configuration to the `%TEMP%` dir)

## Second
1. Delete the directory `%TEMP%\data` and touch a file `%TEMP%\data`.
2. Run the gtests.  `FrameworkTest.CustomConfiguration` will fail again.

# Sequence of calls inside CppMicroServices to trigger the exceptions

- `getFramework()` calls `initOnce()` which sets the persistent storage location (property `FRAMEWORK_STORAGE`) to `%TEMP%` directory.
- `CoreBundleContext` calls `GetFileStorage(this, "data"); `during initialization
   - `GetFileStorage()` takes the path set in `FRAMEWORK_STORAGE` and appends "data", which is `%TEMP%\data`
  - If this directory `%TEMP%\data` doesn't exist, `GetStorageFile()` tries to `_mkdir()` the directory.
    - If the call fails because the directory already exists, it's a no-op.
    - If the call fails due to other reasons, it throws an exception
  - If the path `%TEMP%\data` exists, but it's not accessible,` GetStorageFile()` throws an exception [1]
  - If the path `%TEMP%\data` exists, but it's not a directory, `GetStorageFile()` throws an exception

[1]  Interestingly, on Windows, the `util::Exists()` call succeeds on an inaccessible directory. The underlying `GetFileAttributesW()` returns `FILE_ATTRIBUTE_DIRECTORY 16 (0x10)`. However, the `util::IsDirectory()` returns false `(_stat returns an ENOENT errno)`, and we throw `std::runtime_error("Not a directory")...`

# Bug?

This is probably functioning as designed, but we have been bit by this "mis-behavior" and our customers have run into issues because they either had wrong permissions on `data` directory or they had a file under `%TEMP%` named `data`.

# Potential Solutions

IIUC, `CoreBundleContext` creates this directory for the persistent storage feature of CppMicroServices , which is WIP and not slated for completion in our near future. The following are the potential solutions/workarounds I can think of. Please suggest your preference or any alternate ideas.

- Change the throwing of these particular exceptions to not throw any exceptions.
  - Effort: Minimal.
  - Temporary until we implement persistent storage feature.
- Catch the exceptions in `CoreBundleContext::Init()` surrounding the `GetFileStorage()` call and log them. Change GetFileStorage() call to not create a directory if it doesn't exist.
  - Effort: Minimal.
  - Temporary until we implement persistent storage feature.
- Comment out the `GetFileStorage()` invocation in `CoreBundleContext::Init()`
  - Effort: Minimal.
  - Temporary until we implement persistent storage feature.
  - Added advantage of not creating the stray `%TEMP%\data` directory. 
- Remove all persistent storage code.
  - Effort: Medium.
  - Probably a cleaner solution because it appears that implementing persistent storage isn't in the plans for the near future.

I think the second solution is better for the time being, because the exceptions don't get thrown and the stray `%TEMP%\data` directory isn't created.

**Comment by saschazelzer** [comment]
I agree, the third solution is a good compromise for the time being.
