### ISSUE TITLE
Output exception details (if available) for troubleshooting

### ISSUE THREAD

**Issue by BSipos-RKF** [CppMicroServices/CppMicroServices#27]
In some cases where a `try{} catch{}` block is used to call module code and output error text, there is a separate catch for `std::exception` type to allow printing the exception `what()` message. In other cases, only a catch-all `...` is used.

The specific one I ran into is in `src/service/usServiceListeners.cpp` within `ServiceListeners::ServiceChanged`.

**Comment by saschazelzer** [comment]
Thanks, I will check all try/catch blocks and improve the error reporting.
