### ISSUE TITLE
Main Application "crash" after stopping WebConsole bundle

### ISSUE THREAD

**Issue by m2cci-MJN** [CppMicroServices/CppMicroServices#276]
Hello!

About the WebConsole Bundle, I'm front of a kind of crash.
I used this [example](https://github.com/CppMicroServices/CppMicroServices/blob/development/webconsole/examples/WebConsoleDriver.cpp) you have given.

My goal is to stop dynamically the webconsole servlet.

I tried to "start" usWebConsole, wait 30 sec and "stop" it (in the infinite loop) like in the following code:

```cpp
// ... initialization and starting the framework, the webconsole bundle and the servlet container
int i = 0;
while (true)
{
	SLEEP(1);
	i++;
	if (i == 30)
	{
		std::cout << "timeout" << endl;
		for (auto& b : ctx.GetBundles())
		{
			if (b.GetSymbolicName() == "usWebConsole") 
			{
				b.Stop();
				std::cout << "Bootstrapper stopped" << endl;
			}
		}
	}
}

```
Before 30 sec, the webpage works at localhost:8080/us/console.
After the "stop", when I try to request the console webpage, it stops the main application.

I know Httpfeature is not final but is that the expected behaviour or is it a bug?

**Comment by saschazelzer** [comment]
Hi, this is not expected behaviour for sure. I assume your program crashes, so could you provide a stack trace of the crashing thread? Thanks.

**Comment by m2cci-MJN** [comment]
Hi, my bad, The CppMicroServices library was built without the "thread" option... 
I just add it and there is no crash anymore. 

Thanks for your time, sorry for the inconvenience,

regards, 

Maël

**Comment by saschazelzer** [comment]
Good catch, thank you for your notification.
