### ISSUE TITLE
Clang format improvements

### ISSUE THREAD

**Issue by saschazelzer** [CppMicroServices/CppMicroServices#290]
In #289 we merge an initial Clang format configuration file, but work still needs to be done:

- Modify the config file to more closely match our style
- Update the contribution md file and maybe other docs
- Sanitize the sources according to the final format
- Maybe add a Git pre-commit hook

**Comment by saschazelzer** [comment]
@CppMicroServices/developers I would like to short-cut clang-format discussions and just use a default style without any customization. The "Mozilla" style seems to match ours quite closely and I suggest to go with that one.

**Comment by jeffdiclemente** [comment]
sounds good to me. I have no issues with that.
