### ISSUE TITLE
deadlock in BundleThreads during global static init

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#291]
There is a use case I've encountered whereby if bundle code calls ```Bundle::Start``` while it is being loaded (i.e. during dlopen), a deadlock will occur either while creating a ```std::thread``` (on Windows) or inside the call to ```std::promise::set_value``` (on Linux).

I've created a [bundlethread-deadlock](https://github.com/CppMicroServices/CppMicroServices/tree/bundlethread-deadlock) branch with a reproducible test case. For an unknown reason, this doesn't reproduce on macOS.

**Comment by saschazelzer** [comment]
This looks like being one of the reasons why we moved away from static loading / starting of bundles in 2.x. E.g. on Windows, a global lock (the loader lock) is held when DllMain is called, see https://docs.microsoft.com/en-us/windows/desktop/Dlls/dllmain for details. This quote

> Threads in DllMain hold the loader lock so no additional DLLs can be dynamically loaded or initialized.

nails it. Contructors of global and static object are run in DllMain. Similar restrictions apply to Linux, as far as I know.

**Comment by jeffdiclemente** [comment]
@saschazelzer This begs the question; should we, the CppMicroServices Framework, handle this use case (i.e. starting bundles during global static init). Ideally, I think, global static init shouldn't be used to start bundles.  However, in software ecosystems with large amounts of legacy code, stopping developers from using globals is a non-trivial task.

I think the first question we need to answer is; should CppMicroServices handle this use case (i.e. clients running bundle operations during global static init)? Or, is this a use case which clients need to resolve themselves? What do you think?

**Comment by saschazelzer** [comment]
In 2.x, activators of modules (bundles) were called during static initialization and it led to all kind of subtle errors. It was one of my initial drivers to move away from supporting (well, pretending to support) framework calls / operations during static initialization.

In my opinion, trying to support bundle operations during static init is a dead end. We will open the door for all kind of problems when we call into user code (e.g. activator start) at the latest. Also, only a small subset of OS API is safe to be called during static init, and threading and dynamic lib loading is not among them as far as I know.

**Comment by jeffdiclemente** [comment]
I agree, I do not want to support bundle operations during static init. I think the CppMicroServices documentation could be updated to help make this clear to clients and provide some guidance on how to avoid this use case. 

In addition, I do believe that we can help clients by refactoring the bundle operations code to avoid deadlocks even if clients use static init to perform bundle operations. I'm planning on proposing a RFC with what I have in mind in a couple weeks.

**Comment by saschazelzer** [comment]
Improving the documentation to point this out is definitely good.

A RFC for improvements or safe-guards in that area also sounds good!

**Comment by achristoforides** [comment]
Bundle threads have been removed. Closing this as stale.
