### ISSUE TITLE
Reduce the number of open file handles

### ISSUE THREAD

**Issue by ksubramz** [CppMicroServices/CppMicroServices#299]
Installing thousands of bundles within a process can cause undefined behavior if the OS open file limit has been reached. In our use case, we reached this open file limit on Windows. 

The reason is we read the metadata for the bundle through `mz_zip_reader_init_file` in `BundleResourceContainer::BundleResourceContainer`, which keeps it open until the Bundle is uninstalled (`BundleResourceContainer`'s dtor is called that closes the zip via `mz_zip_reader_end`)

## Proposal

In order to resolve the issue on all platforms i.e. to allow thousands of bundles to be installed into applications:

 1. This solution will close the file handle for the bundle if it only contains a manifest file. The idea is that with only a `manifest.json` file, clients are unlikely to use another CppMicroServices resource API to read meta-data from the .zip file.

 2. If the resource API is used after the bundle is installed, the file will remain open until the bundle is uninstalled.

**Comment by saschazelzer** [comment]
I would like to add another proposal:

3. Bundle resources are accessed using the `BundleResource` and `BundleResourceStream` classes. As long as an instance of one of these classes exists, the file remains open. When the last instance for a specific bundle is destructed, the file is closed.

This approach means that after bundle installation, no file handle is kept (the manifest contents is read into memory and not accessed from the zip anymore).

**Comment by saschazelzer** [comment]
@jeffdiclemente I think it would make the special manifest.json only check obsolete. Anyway, the related PR is a good improvement and we can incrementally improve the file handling.

**Comment by jeffdiclemente** [comment]
@saschazelzer ok, if it simplifies the code and keeps the file handle count down, i'm all for it. I'll look into doing it.
