### ISSUE TITLE
Expose checksum from zip archive.

### ISSUE THREAD

**Issue by mw-cwilcox** [CppMicroServices/CppMicroServices#307]
I'm requesting an enhancement, to expose a checksum of the bundle data.

### Motivation

My team is using CppMicroServices in deployment where DLLs may be loaded, unloaded, and reloaded through the process lifetime, and would like to utilize a checksum to know if a bundle has changed from a prior load.  There is already a 'crc32' in the zip-data, so this seems straightforward to implement.

### Approach

- ('miniz.c' provides 'struct mz_zip_archive_file_stat', which has-a 'mz_uint32 m_crc32;' and is always set in 'mz_zip_reader_file_stat')
- Add a new field to 'BundleResourceContainer::Stat', perhaps 'uint32_t crc32', or 'unsigned int checksum'; the field would be assigned by 'BundleResourceContainer::GetStat', which already has the value inside 'struct mz_zip_archive_file_stat'.
- Add a new getter to 'BundleResource', such as 'uint32_t GetCrc32() const;' or 'unsigned int GetChecksum() const;'.

### Branch

I intend to prototype exactly what I described here on a fork in a feature branch.

**Comment by mw-cwilcox** [comment]
Here's what I was thinking, using 'uint32_t' for the type, and 'GetCrc32' for the method name.

**Comment by ksubramz** [comment]
Thanks Charles. The motivation and the changes you made in your feature branch look fine to me. I am awaiting feedback from other core developers.

**Comment by jeffdiclemente** [comment]
@mw-cwilcox looks good to me. please go ahead and issue a PR to the CppMicroServices development branch.

If you could also add the contents of this issue as a RFC, using the process in https://github.com/CppMicroServices/rfcs, that would be very helpful.

Thanks!

**Comment by jeffdiclemente** [comment]
Fixed in #308
