### ISSUE TITLE
Make ServiceTracker::Close logging more robust

### ISSUE THREAD

**Issue by ksubramz** [CppMicroServices/CppMicroServices#324]
Currently, we do the following logging at the end of the `ServiceTracker::Close()`

```cpp
  if (d->context.GetLogSink()->Enabled())
  {
    if (!d->cachedReference.Load().GetBundle() &&
        d->cachedService.Load() == nullptr)
    {
      DIAG_LOG(*d->context.GetLogSink()) << "ServiceTracker<S,TTT>::close[cached cleared]:"
                    << d->filter;
    }
  }
```
The problem with this is if the context is invalid at this point, `context.GetLogSink()` throws. This exception is thrown even if the logging is disabled. Also, I think no exception should be thrown because this logging is not essential to the `Close`, so it's not an exceptional situation. We should somehow suppress it.

**Comment by jeffdiclemente** [comment]
closing due to #922
