### ISSUE TITLE
How do service consumers know whether to use BundleContext::GetService or ServiceObjects?

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#325]
As a service consumer, its unclear from reading the ```BundleContext::GetService``` documentation when to use ```BundleContext::GetService``` over ```ServiceObjects```. I'm proposing to make a small doc change to ```BundleContext::GetService``` to help users understand when to use one over the other.

**Comment by jeffdiclemente** [comment]
This also begs the question about why two separate APIs exist to get service objects. I see that ```ServiceObjects``` and the concept of service scope was first introduced in OSGi release 6. However I can't find the rationale for why service scope was introduced.
@saschazelzer do you have any insight on why service scopes and the ```ServiceObjects``` class were introduced into OSGi release 6 (i.e. what problem was the OSGi Alliance trying to solve)?

**Comment by saschazelzer** [comment]
@jeffdiclemente I am not aware of the driving use case for the introduction of service scopes in OSGi. My own use case was stateful services. A service would expose an API to configure certain aspects of its behavior and the service instance is then used repeatedly by the same client. A different client should get a new instance, which has not been configured yet. Also, the service was not thread-safe but clients from different threads should be able to use it, so we used "prototype" scope to isolate service instances.

The different API usage is a little unfortunate, I agree. Better documentation would certainly help new users.

**Comment by jeffdiclemente** [comment]
@saschazelzer Supporting stateful services seems like a good reason to introduce a prototype service scope. A google search on "stateful services" found a couple blog posts about how to implement stateful services in OSGi before prototype service scopes existed.
