### ISSUE TITLE
Make CppMicroservices installable via vcpkg

### ISSUE THREAD

**Issue by gdeverlant** [CppMicroServices/CppMicroServices#329]
Hi everyone,

I would like to ask if there is the possibility to be able to install CppMicroservices with the command line utility **vcpkg** which makes package installation really simple.

an example use case would be on the command line:

**vcpkg install cppmicroservices**

Please see : https://github.com/Microsoft/vcpkg

**Comment by jeffdiclemente** [comment]
@gdeverlant This is a great idea. I think this is very useful. If you have time I would encourage you to submit a pull request to vcpkg with the necessary port file to install CppMicroServices. If not, we'll put it on the todo list. 
Thanks!

**Comment by gdeverlant** [comment]
I already achieved 80% of the work but I blocked due to some errors.

**Comment by jeffdiclemente** [comment]
If you let us know what the errors are we can help as best we can.

**Comment by gdeverlant** [comment]
> If you let us know what the errors are we can help as best we can.

I'm creating a branch you can clone and test on your machine. I'm on Windows 10 at the moment.

**Comment by jeffdiclemente** [comment]
I'm not familiar with vcpkg, i'll have to look at the docs first to understand. I'll clone your branch and take a look. thanks.

**Comment by gdeverlant** [comment]
> I'm not familiar with vcpkg, i'll have to look at the docs first to understand. I'll clone your branch and take a look. thanks.

Well you can start where I started : https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-zipfiles.md#tweak-the-generated-portfile

The rest is simple CMake and has nothing to do with **vcpkg**.

**Comment by gdeverlant** [comment]
> @gdeverlant This is a great idea. I think this is very useful. If you have time I would encourage you to submit a pull request to vcpkg with the necessary port file to install CppMicroServices. If not, we'll put it on the todo list.
> Thanks!

Right now I can't make a PR at all until we are finished with fixing the trouble we have now.

**Comment by gdeverlant** [comment]
Here what I did step by step:

1. vcpkg create cppmicroservices https://github.com/CppMicroServices/CppMicroServices/archive/fac24917db6b45226b69c63c26bbd26e297f06e6.zip cppmicroservices-4.0.0.zip
2. vcpkg edit cppmicroservices
3. vcpkg build cppmicroservices

Here is the test project: 
[CMake-multiverses.zip](https://github.com/CppMicroServices/CppMicroServices/files/3003470/CMake-multiverses.zip)

1. cd build
2. cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake

**Comment by gdeverlant** [comment]
Up until now this is the error we encounter:

````
G:\programming\c++\multiverses\build>cmake .. -DCMAKE_TOOLCHAIN_FILE=G:\programming\c++\vcpkg\scripts\buildsystems\vcpkg.cmake
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- Found Magnum: G:/programming/c++/vcpkg/installed/x86-windows/include  found components:  GL Shaders Sdl2Application
-- Found Magnum: G:/programming/c++/vcpkg/installed/x86-windows/include  found components:  GL
CMake Error at G:/programming/c++/vcpkg/installed/x86-windows/share/cppmicroservices4/cmake/CppMicroServicesTargets.cmake:73 (message):
  The imported target "usResourceCompiler" references the file

     "G:/programming/c++/vcpkg/installed/x86-windows/bin/usResourceCompiler4.exe"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "G:/programming/c++/vcpkg/installed/x86-windows/share/cppmicroservices4/cmake/CppMicroServicesTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  G:/programming/c++/vcpkg/installed/x86-windows/share/cppmicroservices4/cmake/CppMicroServicesConfig.cmake:68 (include)
  G:/programming/c++/vcpkg/scripts/buildsystems/vcpkg.cmake:233 (_find_package)
  src/CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "G:/programming/c++/multiverses/build/CMakeFiles/CMakeOutput.log".
````

The root cause of it, it is because we added the following part to the **G:\programming\c++\vcpkg\ports\cppmicroservices\portfile.cmake**

**Code Fix**
````
# Install tools

file(GLOB EXES_DEB
    ${CURRENT_PACKAGES_DIR}/debug/bin/usResourceCompiler*.exe
    ${CURRENT_PACKAGES_DIR}/debug/bin/usShell*.exe
)

file(GLOB EXES_REL
    ${CURRENT_PACKAGES_DIR}/bin/usResourceCompiler*.exe
    ${CURRENT_PACKAGES_DIR}/bin/usShell*.exe
)

# Drop a copy of tools
file(COPY ${EXES_DEB} DESTINATION ${CURRENT_PACKAGES_DIR}/debug/tools)
file(COPY ${EXES_REL} DESTINATION ${CURRENT_PACKAGES_DIR}/tools)

file(REMOVE ${EXES_DEB})
file(REMOVE ${EXES_REL})
````

If we remove those lines from those lines from **G:\programming\c++\vcpkg\ports\cppmicroservices\portfile.cmake** we encounter a previous error we tried to fix with **Code Fix**.

CMake **before** Code Fix: commented lines:

````
# file(GLOB EXES_DEB
    # ${CURRENT_PACKAGES_DIR}/debug/bin/usResourceCompiler*.exe
    # ${CURRENT_PACKAGES_DIR}/debug/bin/usShell*.exe
# )

# file(GLOB EXES_REL
    # ${CURRENT_PACKAGES_DIR}/bin/usResourceCompiler*.exe
    # ${CURRENT_PACKAGES_DIR}/bin/usShell*.exe
# )

# # Drop a copy of tools
# file(COPY ${EXES_DEB} DESTINATION ${CURRENT_PACKAGES_DIR}/debug/tools)
# file(COPY ${EXES_REL} DESTINATION ${CURRENT_PACKAGES_DIR}/tools)

# file(REMOVE ${EXES_DEB})
# file(REMOVE ${EXES_REL})
````

**Comment by jeffdiclemente** [comment]
Thanks for the detailed information.

To summarize so that I understand the current state of adding CppMicroServices to vcpkg...

1. vcpkg does not allow EXEs to be distribution targets
2. the vcpkg devs [have provided guidance](https://github.com/Microsoft/vcpkg/issues/834#issuecomment-288529839) on how to get around this
3. using this workaround, the path to the EXEs are not what the CppMicroServices CMake targets expect because the EXEs were moved.

If all this is true, then the CppMicroServices CMake targets need to be fixed in ```portfile.cmake``` to reference the correct location. Can ```vcpkg_fixup_cmake_targets ``` be used to do this in ```portfile.cmake```? I'd suggest contacting the vcpkg devs. They may have better suggestions on how to fix this. It seems like a fundamental conflict between vcpkg and libraries that want to distribute tooling.

**Comment by gdeverlant** [comment]
To be honest with you I started to learn CMake yesterday all you just mentioned is Chinese to me at this moment. This is the best I can understand but when it comes to technicality and from what it possible actually.

> Thanks for the detailed information.
> 
> To summarize so that I understand the current state of adding CppMicroServices to vcpkg...
> 
> 1. vcpkg does not allow EXEs to be distribution targets
> 2. the vcpkg devs [have provided guidance](https://github.com/Microsoft/vcpkg/issues/834#issuecomment-288529839) on how to get around this
> 3. using this workaround, the path to the EXEs are not what the CppMicroServices CMake targets expect because the EXEs were moved.
> 
> If all this is true, then the CppMicroServices CMake targets need to be fixed in `portfile.cmake` to reference the correct location. Can `vcpkg_fixup_cmake_targets ` be used to do this in `portfile.cmake`? I'd suggest contacting the vcpkg devs. They may have better suggestions on how to fix this. It seems like a fundamental conflict between vcpkg and libraries that want to distribute tooling.

but from your point 1 to 3 it is correct. I don't know how much do we need to change the CppMicroservices CMakeList files or event if we have to do it I don't know. I don't know if this is a bug from **vcpkg** but your intuition might be correct. I need your team to be on this with me as I am learning on the fly.

**Comment by gdeverlant** [comment]
Just to help in the process I tried to compile CppMicroservices directly with CMakeUI on Windows and It went really well. I could link all the debug libs, includes and folders manually and compile that sample project I shared with you. At the end I could run the Multiverses.exe in Debug and Release.

At this point I don't know if the problem is only in the CMakeLists or if the bug is from vcpkg.

I hope this helps.

**Comment by gdeverlant** [comment]
I would suggest that you or a colleague of yours communicate with Microsoft/vcpkg people so that I am not going to find myself in between advanced CMake communication without being able to reply adequately.

I hope you understand my position. In the future when I feel more comfortable with C++ and CMakeList.txt and CMake I will contribute in CppMicroservices. At the moment I'm in learning the basics.

Best regards

**Comment by jeffdiclemente** [comment]
So it sounds like if vcpkg is not used, you are able to build Multiverses without any issues. If vcpkg is used, there are issues which you've described above. Is this an accurate statement?

> I don't know how much do we need to change the CppMicroservices CMakeList files

I'm not suggesting that the CppMicroServices CMakeList files need to be modified. I'm suggesting that the portfile.cmake (which would be a part of vcpkg) needs to be modified. portfile.cmake would tell the CppMicroServices CMakeList files where the correct location of usResourceCompiler EXE is. 

Thanks for your work to help discover this issue and move CppMicroServices closer to being supported in vcpkg.
When we work on this it will help a lot. In the meantime, if at any time in the future you wish to add CppMicroServices to vcpkg, please feel free to do so.

**Comment by gdeverlant** [comment]
> So it sounds like if vcpkg is not used, you are able to build Multiverses without any issues. If vcpkg is used, there are issues which you've described above. Is this an accurate statement?

Yes this is correct without **vcpkg** I was able to create manually a working project.

**Comment by gdeverlant** [comment]
> When we work on this it will help a lot. In the meantime, if at any time in the future you wish to add CppMicroServices to vcpkg, please feel free to do so.

Well I wish I could do more but with only 2 days of knowledge eating and synthesizing this is the farthest I can go unfortunately. I will try to learn more of **CMake** with **vcpkg** and keep you updated when I get something positive. Are you going to communicate with Microsoft?

**Comment by jeffdiclemente** [comment]
If we need to communicate with the vcpkg developers, we will do so. When we look into it, we will know whether this can be worked around or not.

**Comment by gdeverlant** [comment]
> If we need to communicate with the vcpkg developers, we will do so. When we look into it, we will know whether this can be worked around or not.

This sounds really good. I was planning to integrate CppMicroservices to my project with Magnum Engine, OpenGL, ImGui and create dynamic UI App for an invention of mine. Right now every time I modify the CMakeList.txt of Multiverses It regenerates all the Linked resources and I need everytime to redo them manually this doesn't make sense it is counter productive. I hope we can fix this small problem ASAP so that this deal breaker gets out of our way for good.

Best regards.

**Comment by gdeverlant** [comment]
@jeffdiclemente I just had an idea about a way to fix the problem we are having. Since **vcpkg** has trouble dealing with executables how about that we remove the 2 .exe source code from the main core since they are not mandatory for the Framework to run and compile and separate them to another repo and make that one compile itself manually when the tools are necessary.

Am I correct thinking that way? I hope so!

**Comment by jeffdiclemente** [comment]
@gdeverlant usShell4.exe is not needed to build however usResourceCompiler4 is needed to build CppMicroServices bundles. It is responsible for embedding the metadata inside the DLLs needed by the CppMicroServices framework. So I don't think that will work.

**Comment by gdeverlant** [comment]
> @gdeverlant usShell4.exe is not needed to build however usResourceCompiler4 is needed to build CppMicroServices bundles. It is responsible for embedding the metadata inside the DLLs needed by the CppMicroServices framework. So I don't think that will work.

What are you suggesting then?

**Comment by jeffdiclemente** [comment]
I wasn't suggesting anything, simply answering your question.

**Comment by gdeverlant** [comment]
> I wasn't suggesting anything, simply answering your question.

I thought that we can brain storm to maybe come up with something.

**Comment by gdeverlant** [comment]
I think that using an external tool for metadata embedding is not necessary from my point of view. Coming from the Java world we are using @Annotations syntax on classes or member functions within classes.

This is an example of OSGi annotation embedding in Java:

````
@Reference(
  target = "(javax.portlet.name=" + NotificationsPortletKeys.NOTIFICATIONS + ")",
  unbind = "-"
)
protected void setPanelApp(PanelApp panelApp) {
  _panelApp = panelApp;
}
````

You can find more reading the blog post where I found the example: https://community.liferay.com/blogs/-/blogs/liferay-osgi-annotations-what-they-are-and-when-to-use-them

What would be the best is to use the same kind of alternative for C++. I was looking around trying to check if it is possible to use Reflection, Serialization, Annotations with C++11 standard and I found that it is possible. So there is a way to transpose the Java annotation standard to C++ with **https://github.com/cpgf/cpgf**.

The documentation is here : https://github.com/cpgf/cpgf/blob/master/doc/index.md

The metadata principle and its documentation is really good : https://github.com/cpgf/cpgf/blob/master/doc/reflection-using-meta-data-lib.md

What do you think of that?

**Comment by gdeverlant** [comment]
I have also found this other library but it seems to be depending on LLVM for its features: https://github.com/Leandros/metareflect

**Comment by saschazelzer** [comment]
Hi,

I don't think this is the right approach:

> **Code Fix**
> 
> ```
> # Install tools
> 
> file(GLOB EXES_DEB
>     ${CURRENT_PACKAGES_DIR}/debug/bin/usResourceCompiler*.exe
>     ${CURRENT_PACKAGES_DIR}/debug/bin/usShell*.exe
> )
> 
> file(GLOB EXES_REL
>     ${CURRENT_PACKAGES_DIR}/bin/usResourceCompiler*.exe
>     ${CURRENT_PACKAGES_DIR}/bin/usShell*.exe
> )
> 
> # Drop a copy of tools
> file(COPY ${EXES_DEB} DESTINATION ${CURRENT_PACKAGES_DIR}/debug/tools)
> file(COPY ${EXES_REL} DESTINATION ${CURRENT_PACKAGES_DIR}/tools)
> 
> file(REMOVE ${EXES_DEB})
> file(REMOVE ${EXES_REL})
> ```

Instead, in your portfile.cmake, you should configure CppMicroServices to used install paths for its binaries and shared libraries which match the locations which VCPKG expects. Otherwise, if you move (or GLOB) files manually, the *Config.cmake files generated by CppMicroServices will be useless and you would have to resort to a separate FindCppMicroServices script to use the vcpkg port.

I have written a few VPKG ports in the past and if you are willing to share your current efforts, I might be able to help out.

**Comment by saschazelzer** [comment]
> I have also found this other library but it seems to be depending on LLVM for its features: https://github.com/Leandros/metareflect

Please move this discussion to a separate issue, not mixing it with the vcpkg topic here. Also, make sure you read http://docs.cppmicroservices.org/en/stable/framework/doc/resources.html to better understand the requirements for our resources system. Especially, it is not onyl about meta-data, but also embedding arbitrary binary data up to 2GB in size. Any embedded data also needs to be accessible without loading the library which embeds them.

**Comment by gdeverlant** [comment]
> I have written a few VPKG ports in the past and if you are willing to share your current efforts, I might be able to help out.

@saschazelzer Thank you for your feedback on how it is possible to correct this issue. I don't know enough CMake to be able to do what you suggested but If you can provide an example of what you mean you can access the branch that I commited here : https://github.com/gdeverlant/vcpkg/tree/port/cppmicroservices-5801

If you can help and guide with your solution it would be appreciated.


> Please move this discussion to a separate issue, not mixing it with the vcpkg topic here. Also, make sure you read http://docs.cppmicroservices.org/en/stable/framework/doc/resources.html to better understand the requirements for our resources system. Especially, it is not onyl about meta-data, but also embedding arbitrary binary data up to 2GB in size. Any embedded data also needs to be accessible without loading the library which embeds them.

I will create another ticket for that part.

Thanx

**Comment by gdeverlant** [comment]
The part I commited is here :  https://github.com/gdeverlant/vcpkg/tree/port/cppmicroservices-5801/ports/cppmicroservices

**Comment by gdeverlant** [comment]
Alright new findings : by overriding the output path for the 2 **exe** : https://github.com/gdeverlant/CppMicroServices/commit/760f96d9538d5df4e964dd7808fd2e82cb0c7aa9 

I come up with this error

````
G:\programming\c++\multiverses\build>cmake .. -DCMAKE_TOOLCHAIN_FILE=G:\programming\c++\vcpkg\scripts\buildsystems\vcpkg.cmake
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.16.27027.1
-- The CXX compiler identification is MSVC 19.16.27027.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Corrade: G:/programming/c++/vcpkg/installed/x86-windows/include  found components:  Containers rc Utility
-- Found OpenGL: opengl32
-- Found SDL2: optimized;G:/programming/c++/vcpkg/installed/x86-windows/lib/SDL2.lib;debug;G:/programming/c++/vcpkg/installed/x86-windows/debug/lib/SDL2d.lib

-- Found Magnum: G:/programming/c++/vcpkg/installed/x86-windows/include  found components:  GL Shaders Sdl2Application
-- LIB_SUFFIX variable is not defined. It will be autodetected now.
-- You can set it manually with -DLIB_SUFFIX=<value> (64 for example)
-- LIB_SUFFIX autodetected as '', libraries will be installed into C:/Program Files (x86)/Multiverses/lib
-- Found Magnum: G:/programming/c++/vcpkg/installed/x86-windows/include  found components:  GL
-- Found ImGui: G:/programming/c++/vcpkg/installed/x86-windows/include
-- Found MagnumIntegration: G:/programming/c++/vcpkg/installed/x86-windows/include  found components:  ImGui
CMake Error at G:/programming/c++/vcpkg/installed/x86-windows/share/cppmicroservices4/cmake/CppMicroServicesTargets.cmake:73 (message):
  The imported target "usResourceCompiler" references the file

     "G:/programming/c++/vcpkg/installed/x86-windows/bin/usResourceCompiler4.exe"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "G:/programming/c++/vcpkg/installed/x86-windows/share/cppmicroservices4/cmake/CppMicroServicesTargets.cmake"
````

**Comment by gdeverlant** [comment]
I was able to make this work on Windows 10 with CMake and VC++. The code is now working well.

Working code here : https://github.com/gdeverlant/CppMicroServices/commits/port/5801/cppmicroservices

**Comment by gdeverlant** [comment]
Can we close this issue because of https://github.com/microsoft/vcpkg/issues/5801 ?

**Comment by saschazelzer** [comment]
Thanks for triggering this effort. CppMicroservices is now installable via vcpkg.

**Comment by gdeverlant** [comment]
I would like to share my gratitude for having taking the work on your shoulder and completed it.

I could not achieve it alone because I know nothing about CMake.

Best regards.
