### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by airatsa** [CppMicroServices/CppMicroServices#331]
Why doesn't CppMicroServices use Unicode strings? Are there any technical reasons?

**Comment by jeffdiclemente** [comment]
I'm not aware of any technical reasons why unicode can't be used.
@saschazelzer were there any technical reasons for not using unicode initially?

**Comment by jeffdiclemente** [comment]
Thanks Abhinay, I forgot that utf8 is supported via std::string.

@airatsa when you mention unicode strings, what specifically do you mean?

Thanks.

**Comment by karthikreddy09** [comment]
Here’s a link explaining why UTF8 is a better choice over UTF16. http://utf8everywhere.org/

HTH!

Abhinay

**Comment by airatsa** [comment]
> Thanks Abhinay, I forgot that utf8 is supported via std::string.
> 
> @airatsa when you mention unicode strings, what specifically do you mean?

I mean using std::wstring (UTF-16), because Win API is UTF-16.

**Comment by saschazelzer** [comment]
As noted by others, CppMicroServices uses UTF-8 encoding for its internal strings. When it needs to interface with WIN32 API, it converts strings to UTF-16 encoded std::wstring. It is the responsibility of client code to convert between encoding correctly.

Note that embedded resources retain their original encoding, so it is up to the bundle writer to encode resource data properly (e.g. UTF-8 for the manifest.json file).

**Comment by airatsa** [comment]
Thank you for the clarification.
It seems that std:string is entirely unsuitable for utf-8 strings because it treats a string as an array of chars.
Since utf-8 is highly recommended, could you advise a library to work with utf-8 strings?
 
Thank you.

**Comment by saschazelzer** [comment]
A `std::string` is perfectly capable of holding any data, whatever encoding. If you are rather looking for a Unicode library which allows you to iterate over codepoints or do case folding, you might want to look at libicu or something more light-weight.
