### ISSUE TITLE
Building as a subproject

### ISSUE THREAD

**Issue by airatsa** [CppMicroServices/CppMicroServices#342]
It seems that the canonical way of using CppMicroServices is to build it separately, then install and then add via `find_package()`.
I would like to make building CppMicroServices a part of my whole build process, so I added it via `add_subdirectory()`.

```
project(CppMicroServicesTest)
set(CMAKE_CXX_STANDARD_REQUIRED 1)
set(CMAKE_CXX_STANDARD 14)

add_subdirectory(CppMicroServices)
find_package(CppMicroServices CONFIG REQUIRED)
...
```
The folder structure is the following
```
D:\projects\plugins\cppms
  build
  CppMicroServices
  Test_01
```
Everything is fine besides include path to the `GlobalConfig.h` file.
The file had been placed in the `D:\projects\plugins\cppms\build\CppMicroServices\include\cppmicroservices` folder, which looks reasonable, but the path `D:\projects\plugins\cppms\build\CppMicroServices\include` was not added to include path list (but the `D:\projects\plugins\cppms\build` was).
Thus, it looks like I went the wrong way. Does my idea of building CppMicroServices as a subproject have any sense?

**Comment by jeffdiclemente** [comment]
@airatsa I think it makes sense. 
I don't believe that the CppMicroServices build was ever designed to be added to a CMake project in this way (@saschazelzer do you know?).
I'm not saying it can't work, only that changes may be required to make a build work this way.

**Comment by saschazelzer** [comment]
@airatsa Please re-open this issue if you run into more issues.
