### ISSUE TITLE
Question - Micro Service in other Programming Languages

### ISSUE THREAD

**Issue by mohsenomidi** [CppMicroServices/CppMicroServices#358]
Dears, 

As I understood,  this "**CppMicroservice**" is and framework environment that you can develop and  manage all Micorservices that written as a bundle, this engine handle all services in one place and looks like central Management Engine for all bundles. 

In Micro service definition we read: "Services can be implemented using different programming languages, databases, hardware and software environment, depending on what fits best.[1] This does not mean that a single Micro-service is written in a patchwork of programming languages. While it is almost certainly the case that different components that the service is composed of, will require different languages or APIs (example, the web server layer may be in Java or JavaScript, `Wikipedia` "   

In the documentation that i read, i can not find anything about how can i register the Micro-service that written in another language like (Python, Ruby, R, JavaScript (Node.js), Java, and etc... )

would you please clarify about this matter ?

**Comment by saschazelzer** [comment]
Our tagline says

    An OSGi-like C++ dynamic module system and service registry

which you also basically described in your first paragraph. The OSGi concepts predate the "web micro service" hype, which slightly redefined the term "micro service". Like Java is used by OSGi to implement a framework based on those concepts, C++ is used in CppMicorServices. A good explanation is also given here https://stackoverflow.com/questions/49443206/difference-between-osgi-and-microservices .

With CppMicroServices, you can currently only write bundles / services in C++. With the experimental HttpService you could provide a REST interface for a particular service which could then be consumed by any REST client, but as the docs say, it is still experimental.

Hope this helps.

**Comment by mohsenomidi** [comment]
@saschazelzer : thanks for your clarification, as I understand the CppMicroservices is the way to make the application modular, and it is based on OSGi, to achieve the goal, and with this particular architecture we can develop the bundles to achieve the microservice concepts. 

is it correct ?

my second point is an advice for better feature than Http communications via REST.
the main goal of  microservice concepts that gain the better performance and handling the very large scale transaction like social network transactions (TPS: Millions per Sec) in this way if we have a small bottleneck in our interfaces it effected to the performance. 

the Http Rest, is using the HTTP /1.1 and it is not efficient enough, and also most of the data transfer protocol is based in JSON and it is not also efficient, my suggestion is supporting the gRPC for transfer protocol it is based on HTTP/2.0.
HTTP/2.0 is multiplexed, has header compression and is way more efficient than HTTP/1.1.
Also supporting Protobuffer 

The Protobuf advantages: 
very dense data (small output)
hard to robustly decode without knowing the schema (data format is internally ambiguous, and needs schema to clarify)
very fast processing
not intended for human eyes (dense binary)

i think if the CppMicroservice support these options it can be very fast and fit to developing very large scale applications and handling the huge transactions based on Microservice architecture..

Regards,

**Comment by mohsenomidi** [comment]
The answer was enough.
