### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by mohsenomidi** [CppMicroServices/CppMicroServices#365]
Dears, 

I found some memory leaks in micorservice and i just want to share the data with you to make sure about the concerns.

i just add the "debug_new" to the main for finding the memory leak for my own code, and it print many lines about the leakages, then i deiced to add it to the sample code (getting start code) to make sure is it my mistake or not, after execution i just found it happens generally on the main library. 

would you please check and feedback about these leaks the getting start output:

`Started Framework...
Get Bundle...
Bundle Started...
Leaked object at 0x56426bcc9ec0 (size 18, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca350 (size 17, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca3c0 (size 17, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca430 (size 19, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca4a0 (size 23, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca510 (size 21, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca580 (size 24, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca5f0 (size 25, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca670 (size 39, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca6f0 (size 38, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca770 (size 39, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca7f0 (size 45, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca880 (size 49, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca910 (size 35, 0x7fdc1a91ae5a)
Leaked object at 0x56426bcca990 (size 36, 0x7fdc1a91ae5a)
Leaked object at 0x56426bccaa10 (size 43, 0x7fdc1a91ae5a)
Leaked object at 0x56426bccaaa0 (size 20, 0x7fdc1a91ae5a)
Leaked object at 0x56426bccbf90 (size 74, 0x7fdc1a91ae5a)
*** 18 leaks found
delete: freed 0x56426bccbf90 (size 74, 508 bytes still allocated)
delete: freed 0x56426bccaaa0 (size 20, 488 bytes still allocated)
delete: freed 0x56426bccaa10 (size 43, 445 bytes still allocated)
delete: freed 0x56426bcca990 (size 36, 409 bytes still allocated)
delete: freed 0x56426bcca910 (size 35, 374 bytes still allocated)
delete: freed 0x56426bcca880 (size 49, 325 bytes still allocated)
delete: freed 0x56426bcca7f0 (size 45, 280 bytes still allocated)
delete: freed 0x56426bcca770 (size 39, 241 bytes still allocated)
delete: freed 0x56426bcca6f0 (size 38, 203 bytes still allocated)
delete: freed 0x56426bcca670 (size 39, 164 bytes still allocated)
delete: freed 0x56426bcca5f0 (size 25, 139 bytes still allocated)
delete: freed 0x56426bcca580 (size 24, 115 bytes still allocated)
delete: freed 0x56426bcca510 (size 21, 94 bytes still allocated)
delete: freed 0x56426bcca4a0 (size 23, 71 bytes still allocated)
delete: freed 0x56426bcca430 (size 19, 52 bytes still allocated)
delete: freed 0x56426bcca3c0 (size 17, 35 bytes still allocated)
delete: freed 0x56426bcca350 (size 17, 18 bytes still allocated)
delete: freed 0x56426bcc9ec0 (size 18, 0 bytes still allocated)
`

the steps for using the attached files : 
1- copy these files (`debug_new.cpp, debug_new.h, fast_mutex.h, static_assert.h`) "attached to the issue"  into `doc/src/examples/getting_started` 
2- in main file add the include file after all include lines : example :
#include <cppmicroservices/Bundle.h>
#include <cppmicroservices/BundleContext.h>
#include <cppmicroservices/BundleImport.h>
#include <cppmicroservices/Framework.h>
#include <cppmicroservices/FrameworkFactory.h>
**_#include "debug_new.h"_**
3- create CMakeLists.txt for compile and linking the new debug files :
`set(_srcs
  main.cpp
  debug_new.cpp
  )`
4- execute the file (`../../bin/GettingStarted`) 
 it printed the leaks list 

[Debug_SRC_Files.zip](https://github.com/CppMicroServices/CppMicroServices/files/3296867/Debug_SRC_Files.zip)

Regards,

**Comment by jeffdiclemente** [comment]
@mohsenomidi Thanks for taking the time to report this.

Valgrind runs against all the unit tests on Linux during a build. Its hard to tell from the leak checking output above which objects are being leaked. I suspect that these leaks are caused by static strings and other static objects which CppMicroServices uses. Valgrind does a good job of describing which objects leaked and i'd suggest running valgrind on the getting started exe to help confirm/deny this theory.

**Comment by mohsenomidi** [comment]
@jeffdiclemente Thanks for your helpful response. 

Yes you are right, the Valgrind did not report any memory leaks, and i think this is a better tool to use. 

i will close this issue.
