### ISSUE TITLE
Start Async Bundle, is it thread safe for async calls ?

### ISSUE THREAD

**Issue by mohsenomidi** [CppMicroServices/CppMicroServices#369]
Dears, 

I write the service and started it async, for now it is Okay. 

I am using the code below to start bundle 

myBundle = std::async(std::launch::async, [&baseBundle]{ baseBundle.Start(); });

but i found the comment "The Bundle class is not thread safe yet with respect to state changes" in this file : 
framework/test/driver/ConcurrencyTest.cpp

i don't know is it thread safe or not, and if it is not thread safe, how can i start the bundles in async mode ?

**Comment by gdeverlant** [comment]
I don't think you should start any bundle in your code because the framework is responsible of that. If anyhow you are dealing with bundle initialization you are doing something wrong.

**Comment by mohsenomidi** [comment]
The FrameworkFactory is the base class and will handle whole the system, first of all the framework should be initialized and start after that, if we are using the sharedlibs,  we can have bundls, each bundle should be installed and after installation it can be start or stop, this story is the base of the system architecture, as the sample main function ( Ref : [https://github.com/CppMicroServices/CppMicroServices/blob/development/doc/src/tutorial/driver/main.cpp](url) you can find the story that i mentioned above. 

Now my point is about the starting the bundle async, it is very important and want to know if it is not thread safe, how can i handle this ?

**Comment by jeffdiclemente** [comment]
@mohsenomidi The Bundle class is thread safe. The comment in ConcurrencyTest.cpp is old and hasn't been updated. I'll create an issue to update it.

**Comment by saschazelzer** [comment]
As an additional comment, the documentation of the Bundle class explicitly states that `Bundle` class is thread-safe: http://docs.cppmicroservices.org/en/stable/framework/doc/api/main/Bundle.html.
