### ISSUE TITLE
How to use the framework like a *.lib file to compile inside another project?

### ISSUE THREAD

**Issue by al-sabr** [CppMicroServices/CppMicroServices#372]
Greetings again to all!

I would like to know how can I make a DLL in which CppMicroservice is compiled instead of having to depend on the external CppMicroservice.dll file?

Right now I created a Adobe Native Extension (ANE) which is compiled as a DLL but unfortunately CppMicroservice.dll needs to either be in the System32 folder or in the main application path.

My ANE is not able to initialize unless those previous conditions are fullfiled. How can I make it that it get compiled inside of my ANE instead of being external?

Thank you.

Best Regards

**Comment by jeffdiclemente** [comment]
@gdeverlant You can build CppMicroServices as a static library and link that into your ANE. Please see http://docs.cppmicroservices.org/en/stable/framework/doc/static_bundles.html for more details.

As an alternative to static libraries, what about adding the CppMicroServices DLL to the main application path? Is this not possible?

**Comment by gdeverlant** [comment]
> As an alternative to static libraries, what about adding the CppMicroServices DLL to the main application path? Is this not possible?

It is possible but the ANE is not deployed at the same place as the main exe program and because of that both are just ending at 2 different place. I don't want to have to deal with those details that's why.

**Comment by gdeverlant** [comment]
Ok I was able to install with CMake and Visual Studio the CppMicroServices libraries in the C:\Program Files (x86)\CppMicroServices folder. Now when I try to compile my project with the correct includes and libs pointing to that folder I get tons of errors.

![image](https://user-images.githubusercontent.com/26530975/63378711-19aeb680-c393-11e9-9485-0a108664dd1c.png)

It seems that the includes paths allowed in my source code are :

```
#include <cppmicroservices4/cppmicroservices/Bundle.h>
#include <cppmicroservices4/cppmicroservices/BundleContext.h>
```

But what is expected by CppMicroServices is:

```
#include <cppmicroservices/Bundle.h>
#include <cppmicroservices/BundleContext.h>
```

What **vcpkg** installed is as follow:

**C:\vcpkg\packages\cppmicroservices_x86-windows\include\cppmicroservices4\cppmicroservices**

![image](https://user-images.githubusercontent.com/26530975/63379016-ba9d7180-c393-11e9-9499-f0ac3182041b.png)

How do I set CMake to output only **C:\vcpkg\packages\cppmicroservices_x86-windows\include\cppmicroservices** and not that weird path with the version?

**Comment by jeffdiclemente** [comment]
I think what you want to do is add ```C:\vcpkg\packages\cppmicroservices_x86-windows\include\cppmicroservices4``` to the header include search path for your project. This way when CMake compiles your code it will look for header files in ```C:\vcpkg\packages\cppmicroservices_x86-windows\include\cppmicroservices4```, which should resolve such that ```#include <cppmicroservices/Bundle.h>``` is correct. Check the

**Comment by gdeverlant** [comment]
Your message is incomplete...

**Comment by jeffdiclemente** [comment]
whoops, sorry, ignore "Check the".
