### ISSUE TITLE
Add Bundle::GetSymbol API in CppMicroServices 

### ISSUE THREAD

**Issue by gitabhishekdp** [CppMicroServices/CppMicroServices#376]
Bundle should have a Load API that calls LoadLibrary/dlopen on the bundle. Something analogous to Bundle::loadClass in the OSGi Spec. 

see

https://osgi.org/specification/osgi.core/7.0.0/framework.api.html#org.osgi.framework.Bundle.loadClass-String-

&

https://osgi.org/javadoc/r4v43/core/org/osgi/framework/Bundle.html#loadClass(java.lang.String) for details.

In the absence of a Load API, extenders such as Declarative Services have to include the overhead of calling the LoadLibrary/dlopen by themselves. Side effects such as ref count increment and symbol resolution could be avoided if the framework provided the API.

**Comment by gitabhishekdp** [comment]
Adding a placeholder issue for creating the RFC document. I searched but I couldn't find one.

**Comment by gitabhishekdp** [comment]
Relevant [RFC Document](https://github.com/CppMicroServices/rfcs/pull/7/files?utf8=%E2%9C%93&diff=split&w=1&short_path=f037ec6#diff-f037ec6ac8c206f6370d5fcbada3706a) !

**Comment by jeffdiclemente** [comment]
Completed in PR #450
