### ISSUE TITLE
makefile example will crash in CppMicroServices/doc/src/examples/makefile

### ISSUE THREAD

**Issue by NanFeng009** [CppMicroServices/CppMicroServices#379]
#0  cppmicroservices::BundleContextPrivate::CheckValid (this=0x0) at ~/modular_test/external/CppMicroServices/framework/src/bundle/BundleContextPrivate.cpp:69
#1  0x00007ffff7b449fd in cppmicroservices::BundleContext::GetServiceReference (this=0x7fffffffdf80, clazz="IDictionaryService")
    at ~/modular_test/external/CppMicroServices/framework/src/bundle/BundleContext.cpp:204
#2  0x0000555555556a1e in cppmicroservices::BundleContext::GetServiceReference<IDictionaryService> (this=0x7fffffffdf80)
    at ~/modular_test/external/CppMicroServices/local-install/include/cppmicroservices4/cppmicroservices/BundleContext.h:528
#3  0x0000555555556539 in main () at main.cpp:14

**Comment by achristoforides** [comment]
This is not reproducible on the development branch.
