### ISSUE TITLE
Use managed pointers for services, modules and the framework

### ISSUE THREAD

**Issue by saschazelzer** [CppMicroServices/CppMicroServices#38]
With the newly introduced life-cycle of the framework itself and its associated modules, a `Module*` could outlive its association with the framework.

A `Framework*` instance could be shared between different parties.

Service instances currently need to be managed by the registering party. Using shared pointer semantics could ease memory management and keep track of used "handles" from modules within other modules and make `ungetService` calls superfluous.

**Comment by karthikreddy09** [comment]
The services part has been merged to development from 38-smart-pointers-for-services branch. Jeff is working on merging the part related to Bundle objects.
