### ISSUE TITLE
Add FrameworkListener and improve Framework logging

### ISSUE THREAD

**Issue by saschazelzer** [CppMicroServices/CppMicroServices#40]
The logging facility uses a singleton for managing log levels. Initialization is not thread-safe on compilers not supporting magic statics and multiple framework instances cannot be handled.

**Comment by jeffdiclemente** [comment]
These are the requirements for any solution to this issue:

- Logging is thread safe when using a compiler without support for C++ magic statics
- Each framework instance can have its own log level

**Comment by jeffdiclemente** [comment]
@saschazelzer Is it a requirement that any arbitrary bundle, excluding CppMicroServices itself, can use the logger? 

I would imagine that this is not a requirement and that the ```US_DEBUG, US_INFO, US_WARN, and US_ERROR``` log macros are for internal Framework use only. 
A Log service could be created for use by arbitrary bundles if its needed.

**Comment by saschazelzer** [comment]
Initially, the log macros were intended to be used by the framework implementation only. However, it proved to be too convenient and is now used in test bundles and other bundles as well.

I think it would be good to have a simple log service and some public log macros take advantage of it. Some internal log macro usage would probably need to be redone and use some other framework internal mechanism though.

**Comment by jeffdiclemente** [comment]
Thanks @saschazelzer. I'm working on a set of requirements and at least one design based on this information. I'll share the google doc with you soon for discussion and agreement on what to do.

**Comment by saschazelzer** [comment]
Great. I believe this is known / clear, but just in case: The framework requires some logging facility during initialization, before any log service could potentially be available. The typical solution (as in the OSGi specs) are framework events in combination with some implementation specific log mechanism which could make the log entries available to a log service being published later in time. It could also route the log message to the service if available and if not fall back to some internal backend.

**Comment by jeffdiclemente** [comment]
fixed in PR #96
