### ISSUE TITLE
Build errors with gcc 9.2

### ISSUE THREAD

**Issue by michkrom** [CppMicroServices/CppMicroServices#402]
On Ubuntu 19.10 with gcc 9.2, the development branch does not build due to several errors:

home/m/git/CppMicroServices/framework/src/util/LDAPProp.cpp:165:12: error: implicitly-declared ‘cppmicroservices::LDAPPropExpr::LDAPPropExpr(const cppmicroservices::LDAPPropExpr&)’ is deprecated [-Werror=deprecated-copy]
  165 |     return right;
      |            ^~~

**Comment by jeffdiclemente** [comment]
At the time, this was worked around only for mingw in https://github.com/CppMicroServices/CppMicroServices/commit/e89f4dbec82941ca8937dca89a94a6010453707b. This is not solely a mingw issue. See #381 for details.

**Comment by michkrom** [comment]
Yes, the same problem. Is supressing the depreciated-copy warning a right approach? I have added the `=default` copy-constructor and assigment operator and it also worked w/o suppressing the warning globally.

**Comment by jeffdiclemente** [comment]
suppressing the warning is not the right long term solution. The right approach is to either delete, default or user-define the copy constructor/assignment operator.

**Comment by jeffdiclemente** [comment]
Fixed in PR #405
