### ISSUE TITLE
update minimum required CMake version in CMakeLists.txt

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#445]
we currently have 3.2 set as the minimum version of CMake requried to build CppMicroServices however CMake features which require a more recent version are required.

update the minimum required CMake version to be inline with the CMake features currently used.

**Comment by jeffdiclemente** [comment]
documentation also will need to be changed - http://docs.cppmicroservices.org/en/latest/doc/src/build_instructions.html references the minimum required CMake version.

**Comment by ameya7295** [comment]
I will take this task.

**Comment by ameya7295** [comment]
Hi @jeffdiclemente,  
Greetings!

I build the CppMicroServices on RaspberryPi with CMake version 3.13.4, and the build was successful
Keeping the minimum CMake version to 3.13.4

**Comment by ameya7295** [comment]
Hi @jeffdiclemente,  
Greetings!

I build the CppMicroServices on RaspberryPi with CMake version 3.13.4, and the build was successful
Keeping the minimum CMake version to 3.13.4 works.

Singing off: Ameya Patil (ameyapatilr@gmail.com)
