### ISSUE TITLE
Runtime error: Failed to install bundle library at ..../CppMicroServices-3.4.0/build/lib/libeventlistenerd.so: ..../CppMicroServices-3.4.0/build/lib/libeventlistenerd.so does not exist

### ISSUE THREAD

**Issue by techwoes** [CppMicroServices/CppMicroServices#460]
Ubuntu 18.04, AMD 64bit, gcc 7.4, cmake 3.16.5 (tried master and .tar.gz for 3.4)
I have tried every combination of make/cmake/build/set cmake options. Whenever I run usTutorialDriver it fails with the message, also I do not see libeventlistenerd.so anywhere on my PC with a search from / on down

_Failed to install bundle library at ..../CppMicroServices-3.4.0/build/lib/libeventlistenerd.so: ..../CppMicroServices-3.4.0/build/lib/libeventlistenerd.so does not exist_

**Comment by techwoes** [comment]
I found if I build statically by disabling "BUILD_SHARED_LIBS" it seems to run okay at that point.

**Comment by dawidkurzydlo** [comment]
> I found if I build statically by disabling "BUILD_SHARED_LIBS" it seems to run okay at that point.

I have the same problem. Can you explain how to disable this option?
