### ISSUE TITLE
Microservices linked to Executables

### ISSUE THREAD

**Issue by pkampmann** [CppMicroServices/CppMicroServices#464]
Hi developers,

is there a possibility to connect single service implementations to executables? I understood that I could use BundleContext::InstallBundles() to load my service implementation. But the BundleContext only can be instantiated through the Framework Class. So are there multiple framework instantiations allowed and the respective services attached to them will still find each other ?

If that is not the right way to do it, how can I use microservices that are linked to executables ?

Thanks for your help!
Peter

**Comment by jeffdiclemente** [comment]
Hi Peter,

I'm not sure I understand what you mean by "connect single service implementations to executables" and "microservices that are linked to executables ?". Can you elaborate on these concepts?

> So are there multiple framework instantiations allowed and the respective services attached to them will still find each other ?

multiple framework instantiations are allowed however the services contained within each instantiation will not be able to see the services from each other framework instance. Each CppMicroServices framework instance is self-contained and doesn't know about other framework instances. One could create a mechanism by which other framework instances can interact with one another however this is not provided by the CppMicroServices framework.

**Comment by pkampmann** [comment]
Hi Jeff,

thanks for your reply! I want to use the microservices linked to an executable. Looking at the examples, I cannot see how I can do this.

My approach was to write an executable where I link my shared library to which implements the microservice. But then how do I connect the service to a framework so that the services get to know each other?
My first idea was to instantiate a framework with each executable but that does not seem to work. 
So how can I detect running frameworks from an executable and install my service to that ?

Hope this explanation made it clearer :-)

**Comment by saschazelzer** [comment]
Hi Peter,

unless your executable directly depends on symbols (functions, types, etc.) from your shared library, there is no need to link the two. Ideally, your executable and shared libraries implementing or consuming services do not link to each other, except for common service interface types.

In your executable (and only there) you would instantiate a framework instance and call `InstallBundles` providing the path to your shared libraries.

Does that clear things up a little?

**Comment by pkampmann** [comment]
Hi Sascha,

thanks! Yes, thats understood. Sorry, I think I had to be more precise from the beginning. I do have more than one executable each linking a shared library that implements a service. That is where I get the problems with using the framework instance because then I need more than one. 
Is there a solution how do achieve that?

Thanks for your help!

**Comment by saschazelzer** [comment]
Hi, it sounds like you are looking for inter-process communication via services. CppMicroServices does not provide any means to do this easily, sorry. This is typically called "remote services" and involves remote procedure calls in some form, which is a big topic on its own.

**Comment by pkampmann** [comment]
Hi Sascha, thanks for the clarification! I will have a look after these keywords.
