### ISSUE TITLE
Build failes when gtest not installed even without building tests.

### ISSUE THREAD

**Issue by michkrom** [CppMicroServices/CppMicroServices#467]
I am trying to build 3.4.0. It appears that source code in 'complendium' subdirectory explicitly includes gtest even when test build was not called for. And this fails as the gtest is not in the include paths in this case.

**Comment by michkrom** [comment]
One work around would be to replace all
`#include "gtest/test_prod.h"`
with
```
#ifdef GTEST
#include "gtest/gtest_prod.h"
#else
#define FRIEND_TEST(a,b)
#endif
```

The "GTEST" define should be set if gtests are enabled or at least when gtest if found.

**Comment by prabindh** [comment]
I believe this is because of the recursive git inclusion of the googletest project.

**Comment by prabindh** [comment]
I did a `git clone --recurse-submodules https://github.com/CppMicroServices/CppMicroServices`, and all is fine. If a zip is downloaded instead, or just a git clone without recurse, the googletest folder is not downloaded, hence causing this.
