### ISSUE TITLE
Rename 'REGISTERED' macro

### ISSUE THREAD

**Issue by azriel91** [CppMicroServices/CppMicroServices#47]
Hi, I got wxwidgets running as a cppmicroservices module, but while getting it to work, I encountered this issue:

```
...cppmicroservices\core\include\usServiceEvent.h(29): fatal error C1189: #error :
The REGISTERED preprocessor define clashes with the ServiceEvent::REGISTERED enum type. Try to reorder your includes, compile with WIN32_LEAN_AND_MEAN, or undef the REGISTERED macro befor including this header. 
[C:\Users\Azriel\dev\bii\sl_desktop_demo_wx\bii\build\azriel_sl_desktop_demo_wx\azriel_sl_desktop_demo_wx_test_main.vcxproj]
```

If my includes have an `#undef` in the following order, the compilation succeeds:

```
#include "fenix/wxwidgets/wx/wxprec.h"
#ifndef WX_PRECOMP
	#include "fenix/wxwidgets/wx/wx.h"
#endif
#undef REGISTERED

#include <azriel/cppmicroservices/core/include/usModuleRegistry.h>
```

I just noticed, there's a typo: `befor`.

I can make a PR, but what should I call the macro? `US_REGISTERED` has a double meaning.

**Comment by azriel91** [comment]
My mistake, didn't read the error message properly. I don't know what's actually defining the REGISTERED macro - searched all of wx's headers, it wasn't in there, and it isn't mentioned on the msvc website's predefined macros. Might update the ticket later if/when I find what defines it.

**Comment by saschazelzer** [comment]
I forgot the exact header location when we came across this issue. It could be in any of the additional Microsoft headers (e.g. sockets, crypt, etc.) which are included by `windows.h` if `WIN32_LEAND_AND_MEAN` is not defined.
