### ISSUE TITLE
Discord discussion server for all CppMicroServices and general OSGi topics 

### ISSUE THREAD

**Issue by al-sabr** [CppMicroServices/CppMicroServices#507]
I realized that we don't have a gathering platform where we can exchange ideas directly about this project and OSGi in general.

I would like to invite all of you here so that our understanding and knowledge of the OSGi paradigm grows.

Best regards

https://discord.gg/yVmNAbv

**Comment by jeffdiclemente** [comment]
it looks like github has a new feature which accomplishes the same purpose; https://github.com/CppMicroServices/CppMicroServices/discussions.
