### ISSUE TITLE
Please detail how the getting started example can be used

### ISSUE THREAD

**Issue by myfreescalewebpage** [CppMicroServices/CppMicroServices#515]
Hello,

I'm trying to understand how to build and show the getting started "system time" example in action.
I have read documentation and particularly http://docs.cppmicroservices.org/en/stable/doc/src/getting_started.html but it's still not  clear.

Can you detail how to use this example step by step, command by command from "git clone --recursive..." to the execution of the example on the machine.

I'm running Ubuntu but don't care of the OS, easy to find another machine to follow your tutorial.

Thanks,
Joel

**Comment by jeffdiclemente** [comment]
here is an (almost) verbatim set of instructions to run the getting started example:

1. git clone --recursive https://github.com/CppMicroServices/CppMicroServices.git `<path>`
2. cd to `<path>`
3. run the [cmake](https://cmake.org/download/) GUI, provide the path to the CppMicroServices source code folder and a build folder. Then hit the configure button and then make sure to enable `US_BUILD_EXAMPLES` option (see [build instructions](http://docs.cppmicroservices.org/en/stable/doc/src/build_instructions.html) for details on the cmake options available) before hitting the Generate button, which will generate all the Makefiles required to build CppMicroServices.
4. cd to `<build folder>`/doc/src/examples/getting_started
5. run `make` from the command line
6. cd to `<build folder>`/bin
7. run `./GettingStarted ../lib/libServiceTime_SystemClockd.so ../lib/libServiceTime_Consumerd.so` from the command line
you should be the system time output to the terminal. 
I hope this helps.

**Comment by jeffdiclemente** [comment]
closing since an answer was provided. If there are further questions, please use the [Discussions tab](https://github.com/CppMicroServices/CppMicroServices/discussions)
