### ISSUE TITLE
cppmicroservices build failed with warning C4838 in an internal VS version

### ISSUE THREAD

**Issue by Cheney-W** [CppMicroServices/CppMicroServices#517]
I'm a member of Microsoft VCPKG team. 
When we use VCPKG to test an internal version of VS, cppmicroservices build failed with warning C4834: discarding return value of function with 'nodiscard' attribute.
This issue due to the change of STL: https://github.com/microsoft/STL/pull/1495.
For fixing the warning C4834, cppmicroservices need do below change:
In the file: https://github.com/CppMicroServices/CppMicroServices/blob/development/httpservice/src/ServletContainer.cpp
Modify the line 282 and 309 from:
`return Lock(d->m_Mutex), d->m_ContextPath;`
to:
```
Lock l(d->m_Mutex);
US_UNUSED(l);
eturn d->m_ContextPath;
```

**Comment by achristoforides** [comment]
This issue has been addressed in a recent PR (#532 ).

I am going to go ahead and close this issue.
