### ISSUE TITLE
Support LDAP queries against bundle meta-data

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#53]
There is a requirement to be able to start bundles based on the result of LDAP queries against a bundle's embedded meta data (properties).

The OSGi spec seems to already support this capability (i.e. matching based on a map of key/value pairs) within its ```Filter``` interface, which CppMicroServices has implemented as ```LDAPFilter```.

I am proposing that a general "property" class be created, of which ```ServiceProperties``` would derive. ```LDAPFilter``` The general property class will insulate CppMicroServices users from how the framework manages all forms of properties (i.e. service, framework, bundle). 

@CppMicroServices/collaborators A google doc detailing the functional design and requirements will soon follow for review.

This isn't required to be in 3.0, but would need to be in a point release (e.g. 3.x.y) soon after 3.0.

**Comment by kevinleeMW** [comment]
fixed in PR #76
