### ISSUE TITLE
usResourceCompiler needs a verbose option

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#55]
In the current implementation the only way to see some output in the terminal when the resource compiler is run, is by rebuilding the tool with preprocessor flag DEBUG_TRACE set. A command line option "-v" would be helpful.

**Comment by saschazelzer** [comment]
This sounds like a useful addition. Since `-v` is often associated with version information, what do you think about `-V` for verbose and `-VV` for "extra" verbose, e.g. including "debug" output?

**Comment by karthikreddy09** [comment]
I like the idea of verbose levels in general but I think it is an overkill for this tool right now. The single verbose mode fits the need and if there is a requirement in the future to classify the messages, we can consider the very-verbose mode as an enhancement.

Also, with different levels of verbosity we do need guidelines on how to classify the log messages.

I will change the verbose mode short name to "-V" instead of "-v".
