### ISSUE TITLE
Where are the "usSharedData.h" & "usSharedLibrary.h" files I cannot find them anymore.

### ISSUE THREAD

**Issue by al-sabr** [CppMicroServices/CppMicroServices#550]
Can someone provide the information about what happened to these files. I need it with another project to compile and I used the latest version of CppMicroServices and somehow the linking is good but the compiler cannot find the files.

The version of CppMicroServices which is used by the old project is version 2.9.9 : https://phabricator.mitk.org/source/mitk/browse/develop/Modules/CppMicroServices/

What I would like to do is to adapt these files: https://phabricator.mitk.org/source/mitk/browse/develop/Modules/Core/include/mitkEventConfig.h  
https://phabricator.mitk.org/source/mitk/browse/develop/Modules/CppMicroServices/core/src/util/usAtomicInt_p.h  
https://phabricator.mitk.org/source/mitk/browse/develop/Modules/CppMicroServices/core/include/usSharedData.h  
https://phabricator.mitk.org/source/mitk/browse/develop/Modules/CppMicroServices/core/include/usSharedLibrary.h  
https://phabricator.mitk.org/source/mitk/browse/develop/Modules/CppMicroServices/core/src/util/usSharedLibrary.cpp  
https://phabricator.mitk.org/source/mitk/browse/develop/Modules/CppMicroServices/core/src/util/usThreads_p.h

So that it is properly running with the latest version of CppMicroServices which is 3.6.0.

What are the changes or things I have to be careful about?

**Comment by al-sabr** [comment]
I started by this let me know if this makes sense : https://github.com/al-sabr/CTK/commits/ctk-blueberry-port-from-mitk last commits from today.

**Comment by jeffdiclemente** [comment]
it sounds like you have to update the mitk project to use cppms 3.6.0. This is most likely a non-trivial amount of work since there have been many breaking changes since version 2.9.9.
A listing of the changes can be found in the [changelog](https://github.com/CppMicroServices/CppMicroServices/blob/development/CHANGELOG.rst)

you should also read [the migration guide](https://github.com/CppMicroServices/CppMicroServices/wiki/Migration-Guide-to-version-3.0) which also provides a list of what has changed from the context of converting code from cppms 2.x to 3.x.

**Comment by al-sabr** [comment]
I cannot find any infos about what happened to usSharedData.h but I can see that usSharedLibrary.h was renamed to SharedLibrary.h.

I renamed all instance referring to https://github.com/jeffdiclemente/CppMicroServices/issues/1 and https://github.com/CppMicroServices/CppMicroServices/issues/46

I see also that ModuleSettings.h & Auto loading are not documented how to transition...

https://github.com/CppMicroServices/CppMicroServices/pull/30
https://github.com/CppMicroServices/CppMicroServices/issues/75

Or no documentation inside of the Migration concerning this : https://github.com/CppMicroServices/CppMicroServices/issues/39

Also us::InterfaceMap.h is not there also what is the purpose of this? Is it replaced by AnyMap.h

I will need some assistance to achieve my port thank you for your feedback.

**Comment by al-sabr** [comment]
I also have created a link on the MITK bug tracker : https://phabricator.mitk.org/T28454

Can we reopen this thread so that we can follow up?
