### ISSUE TITLE
Compiling on Windows using MSVC generates many warnings (not compiler warnings) about defines

### ISSUE THREAD

**Issue by achristoforides** [CppMicroServices/CppMicroServices#579]
When compiling CppMicroServices on Windows using MSVC 2019 (potentially earlier versions as well), the following message appears after many source files are compiled:

```
Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
- add -D_WIN32_WINNT=0x0601 to the compiler command line; or
- add _WIN32_WINNT=0x0601 to your project's Preprocessor Definitions.
Assuming _WIN32_WINNT=0x0601 (i.e. Windows 7 target).
```

These have been appearing since the inclusion of a subset of boost for the thread pool implementation for DS.

The fix for these is easy (adding a specific define to our compile flags).

The question that is still open is which version define should we use? Should we use what the compiler (and warning) message assumes (Windows 7 target) or should this be something different?

The full set of options can be found here: https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?redirectedfrom=MSDN&view=msvc-160

**Comment by jeffdiclemente** [comment]
I recommend using the assumed Windows 7 target for now.
