### ISSUE TITLE
US_DECLARE_SERVICE_INTERFACE needs a namespace in the inline function definition.

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#58]
Following is the compile error if US_DECLARE_SERVICE_INTERFACE is used in code ...

libSL1/usFooService.h:40:1: error: no template named 'us_service_interface_iid'; did you mean 'us::us_service_interface_iid'?
US_DECLARE_SERVICE_INTERFACE(us::FooService, "us::FooService")

**Comment by karthikreddy09** [comment]
Merged to development branch

**Comment by saschazelzer** [comment]
This was introduced by some older changes of mine, which accidentally moved the `us_declare_service_iid` into the `us` namespace. gcc 4.6 still showed errors after your fix so I changed the code back to not use the `us` namespace.
