### ISSUE TITLE
TestConcurrentBindUnbind Test in usDeclarativeServicesTest TestBindingPolicies.cpp is temporarily disabled.

### ISSUE THREAD

**Issue by pelliott-mathworks** [CppMicroServices/CppMicroServices#584]
The BindingPolicyTest.TestConcurrentBindUnbind test has been temporarily disabled because it sporadically causes an exception in the Windows release build. The exception appears to happen during the Rebind operation when the service being bound has been Unregistered. Will re-enable this test once the problem is fixed.

**Comment by jeffdiclemente** [comment]
closing as this test is no longer disabled.
