### ISSUE TITLE
vcpkg installation don't work

### ISSUE THREAD

**Issue by afinai** [CppMicroServices/CppMicroServices#623]
C:\libs\vcpkg> .\vcpkg.exe install cppmicroservices:x64-windows
Computing installation plan...
The following packages will be built and installed:
    cppmicroservices[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\vcpkg\archives\fb\fbd15c3bb47446ea623a508467c3a9e26eaaab27.zip
Starting package 1/1: cppmicroservices:x64-windows
Building package cppmicroservices[core]:x64-windows...
-- Using cached C:/libs/vcpkg/downloads/CppMicroServices-CppMicroservices-b4d3d404df01d67dfd7fc36111bc5de50e1b89d6.tar.gz
-- Cleaning sources at C:/libs/vcpkg/buildtrees/cppmicroservices/src/e50e1b89d6-8d41542668.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/libs/vcpkg/downloads/CppMicroServices-CppMicroservices-b4d3d404df01d67dfd7fc36111bc5de50e1b89d6.tar.gz
-- Applying patch werror.patch
-- Applying patch fix-dependency-gtest.patch
-- Using source at C:/libs/vcpkg/buildtrees/cppmicroservices/src/e50e1b89d6-8d41542668.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:142 (message):
    Command failed: C:/libs/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/libs/vcpkg/buildtrees/cppmicroservices/x64-windows-dbg
    See logs for more information:
      C:\libs\vcpkg\buildtrees\cppmicroservices\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:93 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/cppmicroservices/portfile.cmake:21 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)
  
Package: cppmicroservices:x64-windows
Vcpkg version: 2020.11.12-nohash

**Comment by al-sabr** [comment]
For me it seems to work for the installation : #677

**Comment by achristoforides** [comment]
Please my comment in https://github.com/CppMicroServices/CppMicroServices/issues/677#issuecomment-1159581761

Apologies for any inconveniences.
