### ISSUE TITLE
Bundle Activator Constructor not found when using statically linked Getting Started

### ISSUE THREAD

**Issue by KarstenB** [CppMicroServices/CppMicroServices#625]
I am basically using the Getting Started example from your documentation, but I am building it statically.
The message I get is `Bundle#2 start failed: Bundle activator constructor not found` and I debugged into the issue. The `dlsym` gets a non-null libHandle and the following symbol: `_us_create_activator_service_time_systemclock` as arguments.  A quick:
```
objdump -x GettingStarted | grep _us_create_activator_service_time_systemclock
000000000014d25e g     F .text  0000000000000056              _us_create_activator_service_time_systemclock
``` 
reveals that the symbol is existing. But the returned `dlerror()` is: `ServicesTest/build/bin/GettingStarted: undefined symbol: _us_create_activator_service_time_systemclock`

I am not quite sure what is going wrong here.

**Comment by KarstenB** [comment]
Addendum: It works if I use BUILD_SHARED_LIBS and it also works if I compile it by adding `add_subdirectory(doc/src/examples/getting_started)` to the projects root CMakeLists.txt file. And set BUILD_SHARED_LIBS to OFF. But I don't understand the difference that causes the failure in my setup.

**Comment by achristoforides** [comment]
Hi @KarstenB , could you describe the exact set of changes that you have made to the code in the case where you receive the message "Bundle#2 start failed: ..."? Are you working out of the GettingStarted directory? Or have you made a separate one?
