### ISSUE TITLE
interaction between two apps based on CppMicroServices

### ISSUE THREAD

**Issue by louislau86** [CppMicroServices/CppMicroServices#629]
Is there any plan for interaction between two apps based on CppMicroServices， such as RPC built-in framework. So, the framework could be used in some distributed scenarios.

**Comment by saschazelzer** [comment]
There are no concrete plans to provide an RPC built-in framework currently. We had occasional discussions about this in the past, but it is not a priority for the main contributors at this point.

However, if an external solution requires changes to the main framework, we are certainly open to accept pull requests to enable such use cases (if the changes are compatible with the current design).

**Comment by al-sabr** [comment]
I created a thread in discussion concerning this.

**Comment by jeffdiclemente** [comment]
closing as we should move further discussions to #636 or a new thread in the `Discussion` section
