### ISSUE TITLE
ServiceRegistration does not unregister a service on destruction of the ServiceRegistration object

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#631]
While a `ServiceRegistration` object is bound to the lifetime of the `Framework` object and the service associated with it will be unregistered when the bundle stops, it would be a good idea to apply RAII to `ServiceRegistration` and unregister the service in the destructor if it wasn't already.

Minimally an update to the documentation informing users to call `ServiceRegistration::Unregister` when they are done with the service would be helpful.

**Comment by tcormackMW** [comment]
There are complications to, at the end of the lifespan of the last `ServiceRegistrationBase`, calling `Unregister` on that service. 

This call could reasonably be made in the destructor of the `ServiceRegistrationBase` and the destructor of the `ServiceRegistrationBasePrivate`. But in either case, it is during the destruction of a `ServiceRegistrationBase` object (The destructor of the `ServiceRegistrationBasePrivate` is made during the destruction of the last `ServiceRegistrationBase` object that owns it). 

Within the call to `Unregister`, as it currently stands, there are calls made to two functions that are potentially problematic:

1. `ServiceRegistry::RemoveServiceRegistration_unlocked(**ServiceRegistrationBase** const& sr)`
2. `ServiceFactory::UngetService(Bundle const& bundle,` 
                                                    `**ServiceRegistrationBase** const& registration,` 
                                                    `InterfaceMapConstPtr const& service)`

Both of these functions take a `ServiceRegistrationBase` object reference as input. The first function, `RemoveServiceRegistration_unlocked`, does not pose significant issues as it primarily serves to erase `ServiceRegistrationBase` objects from various data objects, namely `ServiceRegistry::services` and `ServiceRegistry::serviceRegistrations`. Additionally it interacts with `ServiceRegistrationBasePrivate::properties`. The call to `Unregister` in the new proposal suggests doing so at the end of the lifetime of the final `ServiceRegistrationBase` object, meaning no more of those Base objects exist within `ServiceRegistry::services` and `ServiceRegistry::serviceRegistrations`. The interactions with ServiceRegistrationBasePrivate::properties may need to persist but can be done so without the call to the `ServiceRegistry` object. 

The second function, `ServiceFactory::UngetService`, is a call made to user implemented code. Either option for implementation will need to pass a reference to a `ServiceRegistrationBase` object that is currently within its own destructor. Giving the customer a reference to an object within that objects destructor is a poor implementation.

Even if we were to pass the reference back, there are additional challenges in implementation:

If we make the call from `Unregister` in:

1. `~ServiceRegistrationBase`: we must first confirm that this is the last object with a `shared_ptr` to the same `ServiceRegistrationBasePrivate`, namely that `d.use_count == 1`, and then call `Unregister` only if that is trye. While this is not a problem technically, looking at the use count of a `shared_ptr` goes against its abstraction. 
2. `~ServiceRegistrationBasePrivate`: we will need a reference to the parent `ServiceRegistrationBase` object that is currently being destroyed, but still alive. This could potentially be set in the destructor of _that_ object, but that creates a circular link, first of all, and again breaks abstraction between objects.  

While these solutions may work, passing a reference back to a user to an object currently in its own destructor is dangerous, especially considering the user is able to make copies of that object. This in turn increases the references to the `ServiceRegistrationBasePrivate` object (as each `ServiceRegistrationBase` object has a `shared_ptr` to the `ServiceRegistrationBasePrivate` object) while the `ServiceRegistrationBasePrivate` object is being destroyed.
