### ISSUE TITLE
Discussion about new library that could be used in core features.

### ISSUE THREAD

**Issue by al-sabr** [CppMicroServices/CppMicroServices#633]
Hi! I've stumbeled upon this repo which gave me the idea to ask if it could improve the performances of the internals from cppmicroservices : https://github.com/Squadrick/shadesmar

Do we use some kind of IPC already withing CppMicroServices?

**Comment by jeffdiclemente** [comment]
no IPC mechanism is currently being used within CppMicroServices. 
IPC is mostly applicable to the concept of remote services (i.e. being able to call a service on any machine, even the local one). Remote services is a feature we would like to implement when/if we get the bandwidth to do so.

are there specific operations or workflows that you are finding too slow? If so, we would like to know more specifics about what you are doing and the performance metrics. 

In general, I recommend using the `Discussions` tab at the top of the GitHub page for further discussions on this matter or discussions in general.

**Comment by al-sabr** [comment]
Correct I will move this to discussion it makes more sense. I will continue there but I will still reference this thread at beginning.
