### ISSUE TITLE
ConfigurationAdmin race condition results in duplicate Updated notifications

### ISSUE THREAD

**Issue by pelliott-mathworks** [CppMicroServices/CppMicroServices#644]
If configuration objects are defined in the manifest.json file then the ConfigurationAdminImpl::AddConfigurations method is responsible for adding the configurations to the repository and sending Updated notifications to the services that implement ManagedService, ManagedServiceFactory and ConfigurationListener interfaces. Most of the time that is the only Updated notification sent. There  is one set of circumstances that will result in two Updated notifications being sent for the same configuration object. 

The ConfigurationAdminImpl::AddingService method executes whenever a service that implements a ManagedService or ManagedServiceFactory interface is registered. It is responsible for sending Updated notifications to the service for any configuration objects on which the service is dependent, that already exist in the repository before the service was registered.   There is a race condition between this method and the AddConfigurations method. When the bundle containing the configuration object definitions is started, both AddConfigurations and AddingService will execute. If AddConfigurations runs first and adds a configuration object to the repository, then AddingService sees this object, assumes it was added before the ManagedService or ManagedServiceFactory was registered, and sends an additional Updated notification.

**Comment by jeffdiclemente** [comment]
@pelliott-mathworks  is this still an issue?

**Comment by pelliott-mathworks** [comment]
I don't think so. This was the original race condition that inspired the changes to ConfigurationAdminImpl.cpp AddingService  method. There have been several changes that effect this including the most recent one in 3.7.4 (PR 727)
