### ISSUE TITLE
error whiling building CppMicroServices/doc/src/examples/getting_started/

### ISSUE THREAD

**Issue by alvas** [CppMicroServices/CppMicroServices#646]
$cd CppMicroServices/doc/src/examples/getting_started/
$mkdir build && cd $_
$cmake ..
$make

➜  build git:(development) ✗ sudo make
[  5%] Building CXX object CMakeFiles/ServiceTime.dir/service_time/ServiceTime.cpp.o
[ 10%] Linking CXX static library libServiceTime.a
[ 10%] Built target ServiceTime
[ 15%] Checking resource dependencies for ServiceTime_SystemClock
[ 21%] Checking resource dependencies for ServiceTime_SystemClock
[ 26%] Building CXX object CMakeFiles/ServiceTime_SystemClock.dir/service_time_systemclock/ServiceTimeImpl.cpp.o
[ 31%] Building CXX object CMakeFiles/ServiceTime_SystemClock.dir/ServiceTime_SystemClock/cppmicroservices_resources.cpp.o
[ 36%] Building CXX object CMakeFiles/ServiceTime_SystemClock.dir/ServiceTime_SystemClock/cppmicroservices_init.cpp.o
[ 42%] Linking CXX static library libServiceTime_SystemClock.a
Appending zipped resources to ServiceTime_SystemClock
[ 42%] Built target ServiceTime_SystemClock
[ 47%] Checking resource dependencies for ServiceTime_Consumer
[ 52%] Checking resource dependencies for ServiceTime_Consumer
[ 57%] Building CXX object CMakeFiles/ServiceTime_Consumer.dir/service_time_consumer/ServiceTimeConsumer.cpp.o
[ 63%] Building CXX object CMakeFiles/ServiceTime_Consumer.dir/ServiceTime_Consumer/cppmicroservices_resources.cpp.o
[ 68%] Building CXX object CMakeFiles/ServiceTime_Consumer.dir/ServiceTime_Consumer/cppmicroservices_init.cpp.o
[ 73%] Linking CXX static library libServiceTime_Consumer.a
Appending zipped resources to ServiceTime_Consumer
[ 73%] Built target ServiceTime_Consumer
[ 78%] Checking resource dependencies for GettingStarted
Warning: --bundle-name option is unnecessary here.
[ 84%] Checking resource dependencies for GettingStarted
[ 89%] Building CXX object CMakeFiles/GettingStarted.dir/main.cpp.o
[ 94%] Building CXX object CMakeFiles/GettingStarted.dir/GettingStarted/cppmicroservices_resources.cpp.o
[100%] Linking CXX executable GettingStarted
/usr/bin/ld: cannot open output file GettingStarted: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/GettingStarted.dir/build.make:129: GettingStarted] Error 1
make[1]: *** [CMakeFiles/Makefile2:169: CMakeFiles/GettingStarted.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by achristoforides** [comment]
Hi @alvas , what platform are you trying this on?
