### ISSUE TITLE
Some public/installed headers appear to be unintentional, and some #include non-installed headers

### ISSUE THREAD

**Issue by mrlegowatch** [CppMicroServices/CppMicroServices#67]
At least five installed headers with the suffix "Private" or "_p", that #include non-installed headers (found under core/src), and therefore can't be used by a client. The specific headers are: usBundleHooks_p.h, usBundlePrivate.h, usFrameworkPrivate.h, usServiceHooks_p.h and usServiseListenerHook_p.h. None of these installed headers appear to be required by any other installed headers. There may be additional private headers being installed as well, which probably shouldn't be installed, to prevent any confusion or inadvertent use by clients.

**Comment by saschazelzer** [comment]
Thanks for investigating this. Issue #43 is relaxed to a General Header cleanup and will fix this issue as weil.

**Comment by kevinleeMW** [comment]
Pull Request #118 (which addresses issue #43 ) has been merged into development branch.
