### ISSUE TITLE
Can't you use it like this

### ISSUE THREAD

**Issue by leaningchen** [CppMicroServices/CppMicroServices#708]
1.
![image](https://user-images.githubusercontent.com/63138022/182171378-fb13f19d-cccb-44fe-af15-d575815a5019.png)
![image](https://user-images.githubusercontent.com/63138022/182171791-9a9d1489-7507-4ee1-a3fc-051c07c56041.png)
![image](https://user-images.githubusercontent.com/63138022/182174201-8e9e1695-1ccc-4828-95dc-ec8d786500a2.png)
When the parent class [TMessageLogger] has virtual methods, the module cannot be loaded successfully

2.
![image](https://user-images.githubusercontent.com/63138022/182173215-2a040043-2589-4659-a545-2d3ac867fe86.png)
![image](https://user-images.githubusercontent.com/63138022/182173408-cd6eb5fc-ab21-4dad-8cd0-057cac01530b.png)
![image](https://user-images.githubusercontent.com/63138022/182173828-c39c2d19-7f50-4934-ae85-8b6245a834bf.png)
When the parent class [TMessageLogger] has no virtual method, the module can be loaded successfully

**Comment by leaningchen** [comment]
![image](https://user-images.githubusercontent.com/63138022/182334482-8cf31313-b2c3-42c4-a32d-53c04182b8dd.png)

**Comment by jeffdiclemente** [comment]
@leaningchen  which class is meant to be the service interface and which is the service implementation? Generally, service interfaces need to have pure virtual functions that are then implemented by the service implementation.

**Comment by jeffdiclemente** [comment]
closing for now. I recommend moving this to our discussion tab if more follow up is necessary.
