### ISSUE TITLE
"Rebuild" in Visual Studio solutions causes test failures

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#73]
Rebuild in Visual Studio solution causes test failures. The issue is specific to TestBundleRL. This bundle ends up with no resources in it after a "Rebuild".

**Comment by saschazelzer** [comment]
On what platform did you see this?

There is also a unit test which uses link mode explicitly. Does it run successfully?

**Comment by karthikreddy09** [comment]
I found this when I was testing the autoload feature but this is more generic. Its not a bug in the code but in the cmake files. Happens everytime on windows platform for me.

Repro steps:
1.Configure and Generate the Visual Studio solution
2.Run build on ALL BUILD target
3.Run build on RUN_TESTS target - _all tests pass_.
4.Run clean on ALL_BUILD target
5.Run build on ALL_BUILD target
6.Run build on RUN_TESTS target -_ three test failures. Unable to find bundle name in TestBundleRL_

us_resources.rc for TestBundleRL is initially created during cmake configure phase. The file is blown out when "clean" is run inside the visual studio project. The file gets recreated during the VS rebuild phase but has zero contents. 

Essentially the copying of the file which happens due to "configure_file" (line#143 in usFunctionEmbedResources.cmake) does not run on rebuild. The file gets created with 0 size due to the touch command (line#146 in usFunctionEmbedResources.cmake).

**Comment by karthikreddy09** [comment]
changed the issue description to reflect latest findings.

**Comment by saschazelzer** [comment]
This was fixed with PR #146 .
