### ISSUE TITLE
Separate interfaces and implementation classes in core framework.

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#74]
It would be better to have pure interfaces exposed to clients and have implementaion headers hidden. 

For example, declare the pure abstract class us::Framework in usFramework.h, declare a derived concrete class us::FrameworkImpl in usFrameworkImpl.h and define the concrete class in us::FrameworkImpl. 

Benefits:
1. No need for the private variations of classes. Eg, logic from us::BundlePrivate moves into us::BundleImpl class.
2. we don't expose any unwanted headers like the _p.h files that we expose in the includes directory today. 
3. Allow the clients to create [proxy](https://en.wikipedia.org/wiki/Proxy_pattern) objects.

**Comment by jeffdiclemente** [comment]
removing milestone 3.0 tag. 
We decided that we wouldn't do anything about this, at least in 3.0.

**Comment by saschazelzer** [comment]
I would like to revisit this issue, so what is your current opinion? In my view, hiding private headers can (and is) achieved independently of having pure interfaces at the API layer.

The private classes server the same purpose as the proposed Impl classes, in terms of hiding implementation details and make the public API robust.

Introducing abstract interface classes which only provide pure virtual functions adds the overhead of virtual tables to the whole API, without a direct benefit for the framework. The proxy use case seems to be too uncommon to warrant this, what do you think?

**Comment by jeffdiclemente** [comment]
I agree. I don't think this is something we should try to do at this time.

**Comment by karthikreddy09** [comment]
Yes, I think the headers are cleaner now than when I created this task. Since we do not have any current use cases for Proxy, it looks like there is not much benefit to doing this. I am OK to drop this issue.

**Comment by jeffdiclemente** [comment]
closing stale issue.
