### ISSUE TITLE
ManagedService and ManagedServiceFactory are not notified of configuration removal when the configuration is defined in the same bundle

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#746]
PR #727  caused a regression whereby if a bundle implements a ManagedService and/or ManagedServiceFactory that depends on a configuration which is defined in the same bundle, the ManagedService and/or ManagedServiceFactory will never be notified when said bundle is stopped.

Within the ConfigAdmin implementation, what happens is that the ManagedService and/or ManagedServiceFactory is removed from the vector of services to be notified of a configuration update **BEFORE** the configuration event is sent to the ManagedService and/or ManagedServiceFactory.

use case manifest.json:
```
{
  "bundle.symbolic_name": "ManagedServiceAndFactoryBundle",
  "bundle.name": "ManagedServiceAndFactoryBundle",
  "bundle.activator": false,
  "scr": {
    "version": 1,
    "components": [
      {
        "name": "cppmicroservices::service::cm::test::TestManagedServiceImpl",
        "implementation-class": "cppmicroservices::service::cm::test::TestManagedServiceImpl",
        "properties" : {
          "service.pid" : "cm.testservice"
        },
        "service": {
          "interfaces": [
             "test::TestManagedServiceInterface", "cppmicroservices::service::cm::ManagedService"
          ]
        }
      },
      {
        "name": "cppmicroservices::service::cm::test::TestManagedServiceFactoryImpl",
        "implementation-class": "cppmicroservices::service::cm::test::TestManagedServiceFactoryImpl",
        "properties" : {
          "service.pid" : "cm.testfactory"
        },
        "service": {
          "interfaces": [
            "test::TestManagedServiceFactory", "cppmicroservices::service::cm::ManagedServiceFactory"
          ]
        }
      }
    ]
  },
  "cm": {
    "version": 1,
    "configurations": [
      {
        "pid": "cm.testservice",
        "properties": {
          "anInt": 2
        }
      },
      {
        "pid": "cm.testfactory~config1",
        "properties": {
          "anInt": 2
        }
      },
      {
        "pid": "cm.testfactory~config2",
        "properties": {
          "anInt": 2
        }
      }
    ]
  }
}
```

**Comment by tcormackMW** [comment]
I have looked into this. In the commit prior to #727, commit #725, on a Windows machine, the `ManagedService` is not notified of the configuration removal. On Linux, the `ManagedService` is notified which means that this is not a regression in behavior. Windows and Linux seem to handle this race differently, but behavior is not seemingly changed with commit #727

**Comment by tcormackMW** [comment]
After further investigation, it was concluded that the behavior of non-deterministic ordering of configuration removal and service unregistration during stopping of the bundle was not a regression nor is it incorrect when compared to the OSGI spec.

When running a test case on Debian 11 with a `ManagedService` and it's configuration defined in the same bundle, for example `ConfigAdminTests.testInstallAndStart`, we do indeed see that prior to #727 in #725 the `ManagedService` was always alerted to the removal of a configuration and after commit #727 we see that it is only sporadically notified to the removal of its configuration. 

However, on a Windows Machine running the same test cases, we see that in commit #725 the `ManagedService` is not being alerted to the configuration removal. Given that the notification of configuration removal is not seen in Windows, it was concluded that this is not a guarantied behavior but rather simply a function of the OS's management of threads. 

Additionally, through code inspection, we see that the unregistration of a `ManagedService` and removal of a configuration within the same bundle during that bundles stopping are done concurrently in two threads without synchronization tools to guaranty ordering confirming that the behavior of the `ManagedService` always being alerted to the configuration was never a supported one.
