### ISSUE TITLE
Use of 'bitwise and' to check if a flag is set.

### ISSUE THREAD

**Issue by carneyweb** [CppMicroServices/CppMicroServices#769]
I don't know if this is a real problem or not, but the State enumeration is definitely a uint32_t with different bits representing different states. If it's ever possible to have more than one state bit set at a time, this equality check can fail. If it's NOT possible to have more than one state bit set at a time, why is the enum a bunch of bit flags?

This could really be a problem. Here's the comment from Bundle.h regarding this very thing:

* Values assigned to these states have no specified ordering; they represent
 * bit values that may be ORed together to determine if a bundle is in one of
 * the valid states.

_Originally posted by @carneyweb in https://github.com/CppMicroServices/CppMicroServices/pull/766#discussion_r1047207587_

**Comment by jeffdiclemente** [comment]
see code scanning results for examples: https://github.com/CppMicroServices/CppMicroServices/security/code-scanning

example of this issue: https://github.com/CppMicroServices/CppMicroServices/security/code-scanning/107

**Comment by jeffdiclemente** [comment]
Fixed in PR #849
