### ISSUE TITLE
sprintf is marked as deprecated for MacOS Xcode 14.2

### ISSUE THREAD

**Issue by BuzzwordSea** [CppMicroServices/CppMicroServices#772]
MacOS 13.0.1 Xcode 14.2 CppMicroServices v3.7.4
Configured as
mkdir build; cd build
  cmake -G 'Unix Makefiles' \
  -DCMAKE_INSTALL_PREFIX=/opt/local \
  -DCMAKE_BUILD_TYPE=Debug \
  -DUS_ENABLE_THREADING_SUPPORT=ON \
  -DUS_BUILD_TESTING=1 \
  -DBUILD_SHARED_LIBS=1 \
  -DUS_BUILD_EXAMPLES=1 \
  ..

build: gmake 2>&1 | tee build.log
error:
Building CXX object tools/rc/CMakeFiles/usResourceCompiler.dir/__/__/third_party/jsoncpp.cpp.o
/local/build/CppMicroServices-3.7.4/third_party/jsoncpp.cpp:3869:3: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
  sprintf(formatString, "%%.%dg", precision);
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 error generated.
gmake[2]: *** [tools/rc/CMakeFiles/usResourceCompiler.dir/build.make:104: tools/rc/CMakeFiles/usResourceCompiler.dir/__/__/third_party/jsoncpp.cpp.o] Error 1

-Bob Green  bgreen at mathworks.com

**Comment by jeffdiclemente** [comment]
> **note**: solution should be to replace the use of jsoncpp with rapidjson. rapidjson is used by the rest of the cppmicroservices code base and is faster than jsoncpp.

I was mistaken, jsoncpp is used in both the resource compiler and DS source code generator tools. It's non-trivial to refactor and swap out jsoncpp for rapidjson. The path of least resistance is to upgrade jsoncpp to solve this issue.

**Comment by BuzzwordSea** [comment]
Just FYI. My quick Mac-Only fix was to just call snprintf in place of sprintf.
The code looks like it is already mostly using snprintf so this was a one line
change.

-Bob
