### ISSUE TITLE
Consider using std::shared_ptr instead of raw pointers in usSharedData.h

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#78]
std::shared_ptr can now be used for all instances where `SharedData`, `SharedDataPointer`, and `ExplicitlySharedDataPointer` were used.
Doing this will add robustness to the code base and make maintenance easier.

**Comment by saschazelzer** [comment]
I am not sure I understand this. The mentioned classes implemented the COW pattern (copy on write). `SharedDataPointer` does so implicitly (when calling non-const methods on an object with ref count > 1) and `ExplicitlySharedDataPointer` only detaches a shared instance on explicit request. How can `std::shared_ptr` be used instead while keeping this functionality?

**Comment by jeffdiclemente** [comment]
It helps if I read the code a little more closely...

You're right, the ```SharedDataPointer``` and ```ExplicitlySharedDataPointer``` can't be completely replaced with ```std::shared_ptr``` since they are used for copy-on-write.

After looking again, I can only say that perhaps we should consider using ```std::shared_ptr``` instead of a raw pointer within ```SharedDataPointer``` and ```ExplicitlySharedDataPointer``` to store the shared data object.


Additionally, I think there is a bug in usSharedData.h on line 75:
```inline const T* Data() const { return d; }```.
Shouldn't this be ```inline T* Data() const { return d; }```?

**Comment by jeffdiclemente** [comment]
no longer relevant.
