### ISSUE TITLE
Removing Listeners does not work well

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#83]
we use std::function objects for listeners. 
1. The listener has to be a function pointer. Anything else used does not work. e.g: lamdas
2. When the same service listener is added with different filters, the remove is ambigious

**Comment by jeffdiclemente** [comment]
This is related to #95 as in solving one can also solve the other.

**Comment by jeffdiclemente** [comment]
fixed in PR #179
