### ISSUE TITLE
multiple thread sanitizer issues in usFrameworkTests

### ISSUE THREAD

**Issue by jeffdiclemente** [CppMicroServices/CppMicroServices#846]
These errors are from the test log: https://github.com/CppMicroServices/CppMicroServices/actions/runs/4872584091/jobs/8690974464?pr=845

These issues are reproducible by building the CppMicroServices code base with `US_ENABLE_TSAN` enabled on Linux and running usFrameworkTests repeatedly in a loop.

**Comment by ShivamNegi** [comment]
I can take this up.
