### ISSUE TITLE
Framework fails to activate the bundle inside an executable if the bundle name is not "main"

### ISSUE THREAD

**Issue by karthikreddy09** [CppMicroServices/CppMicroServices#88]
See the email conversation below...

On March 18, 2016 at 8:43 AM, Abhinay Reddyreddy wrote:

Yes, I can work on this. a static string to cache the executable path sounds good to me. 

-Abhinay.

On Mar 18, 2016, at 2:51 AM, Sascha Zelzer <sascha.zelzer@gmail.com> wrote:

Hi Abhinay,

I have been thinking about this for a day and believe you are right. Comparing the bundle location of the caller with the executable path instead of relying on "main" seems to allow us to get rid of the US_BUNDLE_NAME define for the executable completely, Is this something you could work on?

We could add a new "static std::string execPath" member to BundleUtils which is initialized with the executable path during framework initialization.

Cheers,
Sascha

On 03/08/2016 08:42 PM, Abhinay Reddyreddy wrote:
Hi Sascha,
 
At MathWorks, we build test executables by linking all the object files from a bundle into it. The test executable calls InstallBundle on itself. In this scenario, the framework cannot find the activator for the bundle represented by the object files. BundelUtils::GetSymbol only looks in the executable if the bundle name is “main” or the framework is built as static library.
 
Is there a reason why we use the bundle name “main” for symbol look up in an executable ?? Instead of checking for “main” what if we check if the bundle location is the same as the current executable path ?
 
-Abhinay.

**Comment by jeffdiclemente** [comment]
@karthikreddy09 if PR #109 fixes this issue, please close. Thanks.

**Comment by karthikreddy09** [comment]
Fixed in PR #109
