### ISSUE TITLE
Bundle Validation called for every service activation

### ISSUE THREAD

**Issue by ShivamNegi** [CppMicroServices/CppMicroServices#901]
In the current implementation of Bundle Validation the code for validation is being called from 

https://github.com/CppMicroServices/CppMicroServices/blob/f9fd6587f73ea270014e482d6560c3c70c02d4e7/compendium/DeclarativeServices/src/manager/ComponentConfigurationImpl.cpp#L489

Which calls Bundle Validation for each Activation of the bundle service, i.e. if there are four services in a bundle, Bundle Validation will be called four times for the bundle. 

The desired  working is that Bundle Validation is only called for the first loading of the Bundle and not at service activation.

**Comment by jeffdiclemente** [comment]
fixed in PR #921
