### ISSUE TITLE
Headers with "_p.h" suffix do not get resolved in Xcode for automatic-tracking of counterparts

### ISSUE THREAD

**Issue by kevinleeMW** [CppMicroServices/CppMicroServices#93]
Private headers with "_p.h" suffix do not get resolved in Xcode for automatic-tracking of counterparts.

Xcode has a feature that automatically detects source files' counterpart header file and displays it in the assistant editor, as long as the source and header files have the same file name excluding the extension.

Because some source files have their counterpart headers with "_p.h" suffix, Xcode is not able to detect the counterpart headers automatically.

**Comment by saschazelzer** [comment]
There are no `_p.h` headers any more, so I am closing this.

We still have header files where the definitions for symbols live in a differently named `.cpp` file (e.g. a `Some.h` and a `SomePrivate.h` header where all definitions are contained in a common `Some.cpp` file). If this is still an issue, we can consider splitting the `.cpp` file.
